In [8]:
# pip install selenium
# pip install chromedriver-autoinstaller 
# pip install bs4
 
from selenium import webdriver
import chromedriver_autoinstaller
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import time

In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\programdata\anaconda3\envs\pydata\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\programdata\anaconda3\envs\pydata\lib\site-packages (from selenium) (1.26.4)

In [3]:
# 다나와 사이트 검색
options = Options()
options.add_argument('headless'); # headless는 화면이나 페이지 이동을 표시하지 않고 동작하는 모드

In [4]:
# webdirver 설정(Chrome, Firefox 등)
chromedriver_autoinstaller.install()
driver = webdriver.Chrome(options=options) # 브라우저 창 안보이기
# driver = webdriver.Chrome() # 브라우저 창 보이기

In [5]:
# 크롬 브라우저 내부 대기 (암묵적 대기)
driver.implicitly_wait(5)
 
# 브라우저 사이즈
driver.set_window_size(1920,1280)

In [11]:
# driver = Chrome()
driver.get(url)

In [10]:
# 페이지 이동(다나와 유럽 URL)
url = 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362,349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622,468&Month=2021-02-00&MonthTo='

In [13]:
# 페이지 내용
print('Page Contents : {}'.format(driver.page_source))

Page Contents : <html lang="ko"><head>


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="apple-mobile-web-app-title" content="다나와자동차">

<meta name="viewport" content="width=1220">
		<meta name="title" content="판매실적 : 다나와 자동차">
		<meta name="description" content="다나와 자동차의 신차 견적 서비스로 최적의 자동차 구매 방법을 알아 보세요.">
		<meta name="keywords" content=" 국산차, 수입차, 판매량, 판매실적">
		<meta property="og:title" content="판매실적 : 다나와 자동차">
		<meta property="og:image" content="http://autoimg.danawa.com/html/images/danawa_auto_sns.png">
		<meta property="og:url" content="http://auto.danawa.com/newcar/?Work=record&amp;Tab=Top10&amp;Brand=362,349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622,468&amp;Month=2021-05-00&amp;MonthTo=">
		<meta property="og:description" content="다나와 자동차의 신차 견적 서비스로 최적의 자동차 구매 방법을 알아 보세요.">
		<meta property="og:type" content="website">
		<title> 판매실적 : 다나와 자동차 </title><meta name="google-site-verification" content="Zd_kQLEjiNKsk4p5LtRWR2AZFpJf5XlwGsmhy3iAukc">
<meta name="naver-site-verification" content="9157f61cb6b58a315669e72a4bb4fae8ae897cc3">

<link rel="shortcut icon" type="image/x-icon" href="http://img.danawa.com/new/favicon/danawa_favicon.ico">
<link rel="canonical" href="http://auto.danawa.com/newcar/?Work=record&amp;Tab=Top10&amp;Brand=362,349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622,468&amp;Month=2021-05-00&amp;MonthTo=">
<link rel="alternate" href="http://mauto.danawa.com/newcar/?Work=record&amp;Tab=Top10&amp;Brand=362,349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622,468&amp;Month=2021-05-00&amp;MonthTo=">

<script async="" src="//www.google-analytics.com/analytics.js"></script><script async="" src="//tracking.a-bidding.com/js/dmp_roas_simple.min.js?1625489701932" charset="utf-8"></script><script type="text/javascript" src="http://auto.danawa.com/script/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/jquery.ui.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/jquery.cookie.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/jquery.lazyload.min.js"></script>
<script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/danawaLoggingApplicationClientHttps-1.0.0-min.js?ver=1.0.1.25"></script>

<!-- IE6, IE7 css hack -->
<!--[if lt IE 8]>
<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
<![endif]-->

<script type="text/javascript" src="http://auto.danawa.com/script/jsxcompressor.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/chart.js"></script><style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style>
<script type="text/javascript" src="http://auto.danawa.com/script/html2canvas.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/download.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/es6-promise.auto.min.js"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/env.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/common.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/auto.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/community.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/estimate.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/estimateA.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/estimateB.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/estimateC.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/estimateX.js?v=210701095527"></script>
<script type="text/javascript" src="http://auto.danawa.com/script/galleryNew.js?v=210701095527"></script>
<link rel="stylesheet" type="text/css" href="//static.danawa.com/new/recss/auto/common.css?v=210701095527">
<link rel="stylesheet" type="text/css" href="//static.danawa.com/new/recss/auto/home.css?v=210701095527">
<link rel="stylesheet" type="text/css" href="//static.danawa.com/new/recss/auto/theme.css?v=210701095527">
<link rel="stylesheet" type="text/css" href="//static.danawa.com/new/recss/auto/auto.css?v=210701095527">
<link rel="stylesheet" type="text/css" href="//static.danawa.com/css/auto.css?v=210701095527">

<script type="text/javascript">
$(function(){
	$("img.lazyload").lazyload();
});
</script><script type="text/javascript">
	var gnb = 'newcar';
	var lnb = 'record';
	var tab = 'Top10';
	var brand = '362,349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622,468';
	var theme = '';
	var mobile = false;
	var currentDate = '20210705';
    </script>
<script type="text/javascript" src="https://external.impression-neo.naver.com/api/v2/ads/search-jsonp?channel=danawa.ch7&amp;pageSize=5&amp;query=%EC%99%B8%EC%A0%9C%EC%B0%A8%EB%A6%AC%EC%8A%A4&amp;category1=%EC%8B%A0%EC%B0%A8&amp;url=http%3A%2F%2Fauto.danawa.com%2Fnewcar%2F%3FWork%3Drecord%26Tab%3DTop10%26Brand%3D362%2C349%2C371%2C376%2C413%2C422%2C618%2C367%2C459%2C394%2C399%2C381%2C440%2C436%2C445%2C404%2C408%2C409%2C390%2C385%2C622%2C468%26Month%3D2021-05-00%26MonthTo%3D&amp;callback=handle_naver_ads_response"></script></head>
<body>
<div id="autodanawa_wrap">
	<div><a href="#autodanawa_content" class="accessibility" onclick="document.getElementById('autodanawa_content').tabIndex = -1;document.getElementById('autodanawa_content').focus();return false;">본문내용 바로가기</a></div>
<header>
	<div id="autodanawa_header">
		<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@Top1"></script><div class="adverTop" style="background:#c7edf0">
 <div class="cont">
  <a href="http://white.contentsfeed.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/L29/1909264928/Top1/danawa/house_danawacar_top1_115050_1606/danawacar_115050_samsungcard_2.html/446a5348513244692b6b6341446d376a" target="_blank"><img src="http://orange.contentsfeed.com/RealMedia/ads/Creatives/danawa/house_danawacar_top1_115050_1606/danawacar_115050_samsung_card_210629.jpg" alt="다나와x삼성카드 첫 달 할부 이자 지원 이벤트" border="0">
  </a>
 </div>
</div> <img src="http://ad.danawa.com/RealMedia/ads/adstream_lx.ads/www.danawa.com/main_DanawaCar/L29/1909264928/Top1/danawa/house_danawacar_top1_115050_1606/danawacar_115050_samsungcard_2.html/446a5348513244692b6b6341446d376a?_RM_EMPTY_&amp;" style="display:none;" alt="">
		<!-- 퓨어드라이브 -->
		<div id="adver_box_pruedrive" class="housebanner_box">
			<div class="housebanner_contents">
				<div class="movie">
					<iframe id="adver_youtube_pruedrive" title="adver_puredrive" width="908" height="512" src="" data-start="https://www.youtube.com/embed/0jeH13oImbw?rel=0&amp;controls=0&amp;showinfo=0&amp;autoplay=1&amp;playlist=0jeH13oImbw&amp;mute=1&amp;loop=1" frameborder="0" allowfullscreen="true"></iframe>
				</div>
				<div class="banner">
					<h2 class="logo">
						<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_logo.png" alt="PURE DRIVE">
					</h2>
									<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x01"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/97868602/x01/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
					<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x02"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/96706714/x02/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
					<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x03"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/364189521/x03/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
								</div>
				<button id="adver_close_pruedrive" class="btn_close">
					<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_close.png" alt="닫기">
				</button>
			</div>
		</div>

		<!-- 퓨어드라이브2 -->
		<div id="adver_box_pruedrive2" class="housebanner_box">
			<div class="housebanner_contents">
				<div class="movie">
					<iframe id="adver_youtube_pruedrive2" title="adver_puredrive2" width="908" height="512" src="" data-start="https://www.youtube.com/embed/KpmCAFTf6Q4?rel=0&amp;controls=0&amp;showinfo=0&amp;autoplay=1&amp;playlist=KpmCAFTf6Q4&amp;loop=1" frameborder="0" allowfullscreen="true"></iframe>
				</div>
				<div class="banner">
					<h2 class="logo">
						<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_logo.png" alt="PURE DRIVE">
					</h2>
									<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x04"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/169557813/x04/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
					<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x05"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/472896100/x05/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
					<div class="item">
						<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x06"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/1536140462/x06/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
					</div>
								</div>
				<button id="adver_close_pruedrive2" class="btn_close">
					<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_close.png" alt="닫기">
				</button>
			</div>
		</div>

		<!-- 페브리즈-->
		<div id="adver_box_febreze" class="housebanner_box">
			<div class="housebanner_contents">
				<div class="movie">
					<iframe id="adver_youtube_febreze" title="adver_febreze" width="908" height="512" src="" data-start="https://www.youtube.com/embed/Is0Yg70bE60?rel=0&amp;controls=0&amp;showinfo=0&amp;autoplay=1&amp;playlist=Is0Yg70bE60&amp;loop=1" frameborder="0" allowfullscreen="true"></iframe>
				</div>
				<div class="banner">
									<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x04"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/1379280302/x04/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
								</div>
				<button id="adver_close_febreze" class="btn_close">
					<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_close.png" alt="닫기">
				</button>
			</div>
		</div>

		<!-- ZIC 엔진오일 -->
		<div id="adver_box_zic" class="housebanner_box">
			<div class="housebanner_contents">
				<div class="movie">
					<iframe id="adver_youtube_zic" title="adver_zic" width="908" height="512" src="" data-start="https://www.youtube.com/embed/95B56b0-FQc?rel=0&amp;controls=0&amp;showinfo=0&amp;autoplay=1&amp;playlist=95B56b0-FQc&amp;loop=1" frameborder="0" allowfullscreen="true"></iframe>
				</div>
				<div class="banner">
									<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x07"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/1009191234/x07/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
								</div>
				<button id="adver_close_zic" class="btn_close">
					<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_close.png" alt="닫기">
				</button>
			</div>
		</div>

		<!-- 삼성카드 -->
		<div id="adver_box_sscd" class="housebanner_box">
			<div class="housebanner_contents">
				<div class="movie">
					<iframe id="adver_youtube_sscd" title="adver_sscd" width="908" height="512" src="" data-start="https://www.youtube.com/embed/Nx27m9c10Lo?rel=0&amp;controls=0&amp;showinfo=0&amp;autoplay=1&amp;playlist=Nx27m9c10Lo&amp;loop=1" frameborder="0" allowfullscreen="true"></iframe>
				</div>
				<div class="banner">
									<script type="text/javascript" src="http://ad.danawa.com/RealMedia/ads/adstream_jx.ads/www.danawa.com/main_DanawaCar@x04"></script><a href="http://ad.danawa.com/RealMedia/ads/click_lx.ads/www.danawa.com/main_DanawaCar/2057111101/x04/default/empty.gif/446a5348513244692b6b6341446d376a" target="_top"><img src="http://ad.danawa.com/RealMedia/ads/Creatives/default/empty.gif" width="1" height="1" alt="" border="0"></a>
								</div>
				<button id="adver_close_sscd" class="btn_close">
					<img src="http://autoimg.danawa.com/html/images/banner/DA_house_pure_close.png" alt="닫기">
				</button>
			</div>
		</div>

		<iframe src="" name="mouseover_count" title="adver_count" id="adver_count_housebanner" width="0" height="0"></iframe>

		<div class="top">
			<div class="cont">
				<ul class="left">
					<li class="top_mobileApp" data-type="top">
					    <a href="javascript:void(0)" id="title_mobileApp" data-type="top">다나와 앱</a> <!-- 200318 : 접근성 이슈로 인한 링크 추가 -->
					    <div id="mobile_service_layer" class="mobile_service_layer show2" style="display:none;" data-position="top">
				        	<input type="hidden" id="now_mobileApp" value="auto">
				        	<h3 class="screen_out">다나와 앱 서비스 목록</h3>
				        	<div class="gnb_apps_list">
				        		<a href="javascript:void(0);" onclick="getLayerInfo(this,'auto');" class="gnb_apps_link first_gnb_apps active_apps">자동차</a>
				        	</div>
				        	<div class="gnb_apps_conts">
				        		<div class="gnb_apps_imgs" id="layerInfo_auto">
				        			<span class="gnb_appimg_wrap"><img src="http://img.danawa.com/new/danawaApp/img/app6.gif" alt="자동차"></span>
				        			<span class="gnb_apps_txt">대한민국 최대 규모의 정보를 자랑하는 신차견적, 견적평가,<br>중고차 매물 검색, 자동차 뉴스, 커뮤니티 등 자동차 관련<br>소식을 받아보실 수 있습니다.</span>
				        		</div>

				        		<div class="gnb_apps_bottom">
				        			<div class="sms_get_area">
				        				<h4 class="title_gnb_apps">다운로드 URL 문자받기</h4>
				        				<div class="sms_number_area">
				        					<input type="text" maxlength="3" value="" class="input_size_01 input_color_blue" id="smsNumber_first" title="휴대폰 앞자리 입력"><span class="input_bar">-</span>
				        					<input type="text" maxlength="4" value="" class="input_size_01" id="smsNumber_middle" title="휴대폰 중간 네자리 입력"><span class="input_bar">-</span>
				        					<input type="text" maxlength="4" value="" class="input_size_01" id="smsNumber_last" title="휴대폰 끝자리 입력">
				        				</div>

				        				<div class="sms_send_btn">
				        					<button class="btn_sms_send" onclick="sendSmsAppInstall();">보내기</button>
				        				</div>
				        				<p class="txt_sms_01"></p>
				        			</div>

				        			<div class="qr_code_area">
				        				<h4 class="title_gnb_apps">QR코드</h4>
				        				<div class="qr_image_area">
				        					<img id="qrCode_image" alt="자동차 QR코드 http://auto.danawa.com" src="http://img.danawa.com/mobileApp/qrcode/img_autoPush_real.png">
				        				</div>
				        			</div>
				        		</div>
				        		<a href="#mobile_service_layer" class="btn_apps_close"> 닫기</a>
				        	</div>
				        </div>
					</li>
					<li>
						<a href="http://www.danawa.com" target="_blank" onclick="eval('try{ _trk_clickTrace( \'EVT\', \'GNB_다나와 홈_자동차페이지\' ); }catch(_e){ }');">다나와 홈</a>
					</li>
				</ul>
				<ul class="right">

    	<li class="login" id="login">
    		<a href="/social/connect.php?site=combine">로그인</a>
    	</li>
    	<li><a href="https://auth.danawa.com/joinStep1?url=http://www.auto.danawa.com">다나와 회원가입</a></li>					<li><a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_이벤트\' ); }catch(_e){ }');" href="/event/?Work=list">이벤트</a></li>
					<li><a href="/help/">이용안내</a></li>
				</ul>
			</div>
		</div>
		<div class="main">
			<div class="cont">
							<div class="logo danawa "><a href="http://www.danawa.com" target="_blank"><span class="screen_behind">다나와</span></a></div>
				<h1 class="logo auto "><a href="/"><span class="screen_behind">다나와 자동차</span></a></h1>
				<div class="search">
					<input type="hidden" id="originSearchWord" title="검색어" value="">
					<input type="text" id="searchWord" title="검색어" value="" placeholder="검색어 입력" road="1">
					<button type="button" onclick="goSearch('')"><span class="screen_behind">검색</span></button>
					<div id="search_preview"></div>
				</div>


                            <div class="banner">
    							<a href="/newcar/?Work=sales&amp;refer=homehouse"><img src="http://autoimg.danawa.com/html/images/banner/search_right_banner_07.jpg" alt="07월 판매조건 확인하기"></a>
    						</div>
			</div>
		</div>
		<div class="gnb">
			<div class="cont">
                <!-- 신차개편 : 신규코딩 -->
                <div class="gnb__list "><!-- 신차개편 : 메뉴명 hover, focus시 gnb--hover 클래스 추가 -->
                    <div class="gnb__col gnb__rent ">
                        <a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_렌트/리스_전체\' ); }catch(_e){ }');" href="/leaserent/" class="item"><span class="icon"></span><span class="blind">렌트리스</span></a>
                        <div class="sub">
                            <ul class="snb">
                                <li class="snb__item"><a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_렌트/리스_가격비교\' ); }catch(_e){ }');" href="/leaserent/?Work=leaserentSearch">가격비교</a></li>
                                <li class="snb__item"><a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_렌트/리스_직영몰 혜택\' ); }catch(_e){ }');" href="/leaserent/?Work=leaserentBenefit">직영몰 혜택</a></li>
                                <li class="snb__item"><a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_렌트/리스_특가판매\' ); }catch(_e){ }');" href="/leaserent/?Work=special">직영몰 특가</a></li>
                                <li class="snb__item"><a onclick="eval('try{ _trk_clickTrace( \'EVT\', \'자동차_GNB_렌트/리스_직영몰 상담 현황\' ); }catch(_e){ }');" href="/leaserent/?Work=directMallBuyCounseling">직영몰 상담 현황</a></li>

In [20]:
from selenium.webdriver.support.ui import Select

In [35]:
select = Select(driver.find_element_by_id('selDay'))#  월 선택
select.select_by_visible_text('01월')# 드롭다운 메뉴 값 선택 1월~12월까지

In [37]:
#bs4 초기화
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [47]:
# 상품 리스트 선택
temp = soup.find_all('table')
temp

[<table cellspacing="0" class="recordTable model">
 <caption>모델별 판매실적</caption>
 <colgroup>
 <col class="check"/>
 <col class="rank"/>
 <col class="more"/>
 <col width="*"/>
 <col class="count"/>
 <col class="rate"/>
 <col class="comp"/>
 <col class="comp"/>
 </colgroup>
 <thead>
 <tr>
 <th colspan="3"> </th>
 <th scope="col">모델</th>
 <th scope="col">판매량</th>
 <th scope="col">점유율</th>
 <th scope="col">전월대비</th>
 <th scope="col">전년대비</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td><input brand="349" name="compItemCk" title="The New E-Class" type="checkbox" value="record_3757"/></td>
 <td class="rank">1</td>
 <td><button class="viewMore" model="3757" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3757" target="_blank">
 <img alt="The New E-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3757/model_200.png"/>
                                 The New E-Class
                             </a>
 </td>
 <td class="num">2,745<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3757"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">14.9%</td>
 <td class="right">5,905<span class="down">3,160▼</span></td>
 <td class="right">0<span class="up">2,745▲</span></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E220d 4MATIC</span></td>
 <td class="num">356</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E250</span></td>
 <td class="num">1,205</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E300e 4MATIC</span></td>
 <td class="num">344</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E350 4MATIC</span></td>
 <td class="num">802</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC</span></td>
 <td class="num">9</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC Cabriolet</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC Coupe</span></td>
 <td class="num">20</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG E53 4MATIC+</span></td>
 <td class="num">3</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG E53 4MATIC+ Coupe</span></td>
 <td class="num">5</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">2,745</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>2,045</strong></span><span>경유 <strong>356</strong></span><span>하이브리드 <strong>344</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="5 Series" type="checkbox" value="record_3901"/></td>
 <td class="rank">2</td>
 <td><button class="viewMore" model="3901" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3901" target="_blank">
 <img alt="5 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3901/model_200.png"/>
                                 5 Series
                             </a>
 </td>
 <td class="num">1,730<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3901"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">9.4%</td>
 <td class="right">1,458<span class="up">272▲</span></td>
 <td class="right">0<span class="up">1,730▲</span></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>520i</span></td>
 <td class="num">622</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>523d</span></td>
 <td class="num">106</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>523d xDrive</span></td>
 <td class="num">83</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i</span></td>
 <td class="num">413</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i xDrive</span></td>
 <td class="num">258</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530e</span></td>
 <td class="num">211</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>540i xDrive</span></td>
 <td class="num">22</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M550i xDrive</span></td>
 <td class="num">15</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">1,730</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>1,330</strong></span><span>경유 <strong>189</strong></span><span>하이브리드 <strong>211</strong></span></td></tr>
 <tr>
 <td><input brand="371" name="compItemCk" title="A6" type="checkbox" value="record_3713"/></td>
 <td class="rank">3</td>
 <td><button class="viewMore" model="3713" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3713" target="_blank">
 <img alt="A6" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3713/model_200.png"/>
                                 A6
                             </a>
 </td>
 <td class="num">1,096<button brand="371" class="viewGraph" name="viewGraph" type="button" val="3713"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">6.0%</td>
 <td class="right">965<span class="up">131▲</span></td>
 <td class="right">318<span class="up">778▲</span></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40 TDI</span></td>
 <td class="num">141</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40 TDI quattro</span></td>
 <td class="num">93</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TDI quattro</span></td>
 <td class="num">55</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TFSI</span></td>
 <td class="num">425</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TFSI quattro</span></td>
 <td class="num">354</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>50 TDI quattro</span></td>
 <td class="num">15</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>S6 TDI</span></td>
 <td class="num">13</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">1,096</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>779</strong></span><span>경유 <strong>317</strong></span></td></tr>
 <tr>
 <td><input brand="349" name="compItemCk" title="A-Class" type="checkbox" value="record_3691"/></td>
 <td class="rank">4</td>
 <td><button class="viewMore" model="3691" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3691" target="_blank">
 <img alt="A-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3691/model_200.png"/>
                                 A-Class
                             </a>
 </td>
 <td class="num">832<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3691"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">4.5%</td>
 <td class="right">506<span class="up">326▲</span></td>
 <td class="right">20<span class="up">812▲</span></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A200d</span></td>
 <td class="num">64</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A220</span></td>
 <td class="num">229</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A220 Sedan</span></td>
 <td class="num">430</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A250 4MATIC</span></td>
 <td class="num">30</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG A35 4MATIC</span></td>
 <td class="num">31</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG A45 4MATIC</span></td>
 <td class="num">48</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">832</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>768</strong></span><span>경유 <strong>64</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="3 Series" type="checkbox" value="record_3520"/></td>
 <td class="rank">5</td>
 <td><button class="viewMore" model="3520" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3520" target="_blank">
 <img alt="3 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3520/model_200.png"/>
                                 3 Series
                             </a>
 </td>
 <td class="num">593<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3520"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">3.2%</td>
 <td class="right">791<span class="down">198▼</span></td>
 <td class="right">265<span class="up">328▲</span></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320i</span></td>
 <td class="num">369</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320i Touring</span></td>
 <td class="num">25</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d</span></td>
 <td class="num">57</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d Touring</span></td>
 <td class="num">21</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d xDrive</span></td>
 <td class="num">18</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>330e</span></td>
 <td class="num">53</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M340i</span></td>
 <td class="num">34</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M340i xDrive Touring</span></td>
 <td class="num">16</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">593</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>444</strong></span><span>경유 <strong>96</strong></span><span>하이브리드 <strong>53</strong></span></td></tr>
 <tr>
 <td><input brand="376" name="compItemCk" title="Tiguan" type="checkbox" value="record_3368"/></td>
 <td class="rank">6</td>
 <td><button class="viewMore" model="3368" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3368" target="_blank">
 <img alt="Tiguan" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3368/model_200.png"/>
                                 Tiguan
                             </a>
 </td>
 <td class="num">565<button brand="376" class="viewGraph" name="viewGraph" type="button" val="3368"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">3.1%</td>
 <td class="right">327<span class="up">238▲</span></td>
 <td class="right">564<span class="up">1▲</span></td>
 </tr>
 <tr class="sub model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>2.0 TDI</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>Allspace 2.0 TDI</span></td>
 <td class="num">564</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">565</td>
 <td class="total_cont" colspan="3"><span>경유 <strong>565</strong></span></td></tr>
 <tr>
 <td><input brand="349" name="compItemCk" title="GLC-Class" type="checkbox" value="record_3707"/></td>
 <td class="rank">7</td>
 <td><button class="viewMore" model="3707" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3707" target="_blank">
 <img alt="GLC-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3707/model_200.png"/>
                                 GLC-Class
                             </a>
 </td>
 <td class="num">467<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3707"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.5%</td>
 <td class="right">1,108<span class="down">641▼</span></td>
 <td class="right">788<span class="down">321▼</span></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC220d 4MATIC</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC220d 4MATIC Coupe</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC300e 4MATIC</span></td>
 <td class="num">254</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC300e 4MATIC Coupe</span></td>
 <td class="num">204</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG GLC43 4MATIC</span></td>
 <td class="num">7</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">467</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>7</strong></span><span>경유 <strong>2</strong></span><span>하이브리드 <strong>458</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="X5" type="checkbox" value="record_3577"/></td>
 <td class="rank">8</td>
 <td><button class="viewMore" model="3577" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3577" target="_blank">
 <img alt="X5" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3577/model_200.png"/>
                                 X5
                             </a>
 </td>
 <td class="num">466<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3577"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.5%</td>
 <td class="right">424<span class="up">42▲</span></td>
 <td class="right">210<span class="up">256▲</span></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>
 <td class="num">189</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40i</span></td>
 <td class="num">177</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40d</span></td>
 <td class="num">44</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45e</span></td>
 <td class="num">35</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M50i</span></td>
 <td class="num">21</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">466</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>198</strong></span><span>경유 <strong>233</strong></span><span>하이브리드 <strong>35</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="X6" type="checkbox" value="record_3761"/></td>
 <td class="rank">9</td>
 <td><button class="viewMore" model="3761" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3761" target="_blank">
 <img alt="X6" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3761/model_200.png"/>
                                 X6
                             </a>
 </td>
 <td class="num">415<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3761"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.3%</td>
 <td class="right">313<span class="up">102▲</span></td>
 <td class="right">70<span class="up">345▲</span></td>
 </tr>
 <tr class="sub model_3761" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>

In [50]:
!pip install html_table_parser

Collecting html_table_parser
  Downloading html_table_parser-0.1.0.tar.gz (3.4 kB)
Collecting beautifulsoup4==4.4.1
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81 kB)
Building wheels for collected packages: html-table-parser
  Building wheel for html-table-parser (setup.py): started
  Building wheel for html-table-parser (setup.py): finished with status 'done'
  Created wheel for html-table-parser: filename=html_table_parser-0.1.0-py3-none-any.whl size=4646 sha256=b01e0a05e8f22f805d0085dcf0da439b0e2c235d6acf759760eb49eaaf250c65
  Stored in directory: c:\users\tjfsu\appdata\local\pip\cache\wheels\8b\db\ba\ffbb0a5dcb78fd955a33d26295a77ced593e712a7d8a4a0dc6
Successfully built html-table-parser
Installing collected packages: beautifulsoup4, html-table-parser
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.3
    Uninstalling beautifulsoup4-4.9.3:
      Successfully uninstalled beautifulsoup4-4.9.3
Successfully installed beautifulsoup4-4.4.1 html-table-parser-0.1.0

In [57]:
from html_table_parser import parser_functions as parser

In [59]:
p = parser.make2d(temp[0])
p

[['', '', '', '모델', '판매량', '점유율', '전월대비', '전년대비'],
 ['',
  '1',
  '등급별 보기',
  'The New E-Class',
  '2,745그래프로 보기',
  '14.9%',
  '5,9053,160▼',
  '02,745▲'],
 ['', '', '', 'E220d 4MATIC', '356', '', '', ''],
 ['', '', '', 'E250', '1,205', '', '', ''],
 ['', '', '', 'E300e 4MATIC', '344', '', '', ''],
 ['', '', '', 'E350 4MATIC', '802', '', '', ''],
 ['', '', '', 'E450 4MATIC', '9', '', '', ''],
 ['', '', '', 'E450 4MATIC Cabriolet', '1', '', '', ''],
 ['', '', '', 'E450 4MATIC Coupe', '20', '', '', ''],
 ['', '', '', 'AMG E53 4MATIC+', '3', '', '', ''],
 ['', '', '', 'AMG E53 4MATIC+ Coupe', '5', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '2,745',
  '휘발유 2,045경유 356하이브리드 344',
  '휘발유 2,045경유 356하이브리드 344',
  '휘발유 2,045경유 356하이브리드 344'],
 ['',
  '2',
  '등급별 보기',
  '5 Series',
  '1,730그래프로 보기',
  '9.4%',
  '1,458272▲',
  '01,730▲'],
 ['', '', '', '520i', '622', '', '', ''],
 ['', '', '', '523d', '106', '', '', ''],
 ['', '', '', '523d xDrive', '83', '', '', ''],
 ['', '', '', '530i', '413', '', '', ''],
 ['', '', '', '530i xDrive', '258', '', '', ''],
 ['', '', '', '530e', '211', '', '', ''],
 ['', '', '', '540i xDrive', '22', '', '', ''],
 ['', '', '', 'M550i xDrive', '15', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '1,730',
  '휘발유 1,330경유 189하이브리드 211',
  '휘발유 1,330경유 189하이브리드 211',
  '휘발유 1,330경유 189하이브리드 211'],
 ['', '3', '등급별 보기', 'A6', '1,096그래프로 보기', '6.0%', '965131▲', '318778▲'],
 ['', '', '', '40 TDI', '141', '', '', ''],
 ['', '', '', '40 TDI quattro', '93', '', '', ''],
 ['', '', '', '45 TDI quattro', '55', '', '', ''],
 ['', '', '', '45 TFSI', '425', '', '', ''],
 ['', '', '', '45 TFSI quattro', '354', '', '', ''],
 ['', '', '', '50 TDI quattro', '15', '', '', ''],
 ['', '', '', 'S6 TDI', '13', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '1,096',
  '휘발유 779경유 317',
  '휘발유 779경유 317',
  '휘발유 779경유 317'],
 ['', '4', '등급별 보기', 'A-Class', '832그래프로 보기', '4.5%', '506326▲', '20812▲'],
 ['', '', '', 'A200d', '64', '', '', ''],
 ['', '', '', 'A220', '229', '', '', ''],
 ['', '', '', 'A220 Sedan', '430', '', '', ''],
 ['', '', '', 'A250 4MATIC', '30', '', '', ''],
 ['', '', '', 'AMG A35 4MATIC', '31', '', '', ''],
 ['', '', '', 'AMG A45 4MATIC', '48', '', '', ''],
 ['', '', '', '총합계 :', '832', '휘발유 768경유 64', '휘발유 768경유 64', '휘발유 768경유 64'],
 ['', '5', '등급별 보기', '3 Series', '593그래프로 보기', '3.2%', '791198▼', '265328▲'],
 ['', '', '', '320i', '369', '', '', ''],
 ['', '', '', '320i Touring', '25', '', '', ''],
 ['', '', '', '320d', '57', '', '', ''],
 ['', '', '', '320d Touring', '21', '', '', ''],
 ['', '', '', '320d xDrive', '18', '', '', ''],
 ['', '', '', '330e', '53', '', '', ''],
 ['', '', '', 'M340i', '34', '', '', ''],
 ['', '', '', 'M340i xDrive Touring', '16', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '593',
  '휘발유 444경유 96하이브리드 53',
  '휘발유 444경유 96하이브리드 53',
  '휘발유 444경유 96하이브리드 53'],
 ['', '6', '등급별 보기', 'Tiguan', '565그래프로 보기', '3.1%', '327238▲', '5641▲'],
 ['', '', '', '2.0 TDI', '1', '', '', ''],
 ['', '', '', 'Allspace 2.0 TDI', '564', '', '', ''],
 ['', '', '', '총합계 :', '565', '경유 565', '경유 565', '경유 565'],
 ['',
  '7',
  '등급별 보기',
  'GLC-Class',
  '467그래프로 보기',
  '2.5%',
  '1,108641▼',
  '788321▼'],
 ['', '', '', 'GLC220d 4MATIC', '1', '', '', ''],
 ['', '', '', 'GLC220d 4MATIC Coupe', '1', '', '', ''],
 ['', '', '', 'GLC300e 4MATIC', '254', '', '', ''],
 ['', '', '', 'GLC300e 4MATIC Coupe', '204', '', '', ''],
 ['', '', '', 'AMG GLC43 4MATIC', '7', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '467',
  '휘발유 7경유 2하이브리드 458',
  '휘발유 7경유 2하이브리드 458',
  '휘발유 7경유 2하이브리드 458'],
 ['', '8', '등급별 보기', 'X5', '466그래프로 보기', '2.5%', '42442▲', '210256▲'],
 ['', '', '', '30d', '189', '', '', ''],
 ['', '', '', '40i', '177', '', '', ''],
 ['', '', '', '40d', '44', '', '', ''],
 ['', '', '', '45e', '35', '', '', ''],
 ['', '', '', 'M50i', '21', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '466',
  '휘발유 198경유 233하이브리드 35',
  '휘발유 198경유 233하이브리드 35',
  '휘발유 198경유 233하이브리드 35'],
 ['', '9', '등급별 보기', 'X6', '415그래프로 보기', '2.3%', '313102▲', '70345▲'],
 ['', '', '', '30d', '160', '', '', ''],
 ['', '', '', '40i', '190', '', '', ''],
 ['', '', '', '40d', '33', '', '', ''],
 ['', '', '', 'M50i', '32', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '415',
  '휘발유 222경유 193',
  '휘발유 222경유 193',
  '휘발유 222경유 193'],
 ['', '10', '등급별 보기', 'Cayenne', '393그래프로 보기', '2.1%', '42835▼', '16377▲'],
 ['', '', '', 'Cayenne', '234', '', '', ''],
 ['', '', '', 'Cayenne Coupe', '150', '', '', ''],
 ['', '', '', 'Cayenne E-Hybrid', '1', '', '', ''],
 ['', '', '', 'Cayenne Turbo Coupe', '8', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '393',
  '휘발유 392하이브리드 1',
  '휘발유 392하이브리드 1',
  '휘발유 392하이브리드 1'],
 ['', '11', '등급별 보기', 'X1', '388그래프로 보기', '2.1%', '29692▲', '46342▲'],
 ['', '', '', '18d', '51', '', '', ''],
 ['', '', '', '20i', '337', '', '', ''],
 ['', '', '', '총합계 :', '388', '휘발유 337경유 51', '휘발유 337경유 51', '휘발유 337경유 51'],
 ['', '12', '등급별 보기', 'Arteon', '348그래프로 보기', '1.9%', '85263▲', '1,189841▼'],
 ['', '', '', '2.0 TDI', '275', '', '', ''],
 ['', '', '', '2.0 TDI 4Motion', '73', '', '', ''],
 ['', '', '', '총합계 :', '348', '경유 348', '경유 348', '경유 348'],
 ['', '13', '등급별 보기', 'CLS-Class', '345그래프로 보기', '1.9%', '522177▼', '569224▼'],
 ['', '', '', 'CLS300d', '9', '', '', ''],
 ['', '', '', 'CLS450 4MATIC', '320', '', '', ''],
 ['', '', '', 'AMG CLS53 4MATIC+', '16', '', '', ''],
 ['', '', '', '총합계 :', '345', '휘발유 336경유 9', '휘발유 336경유 9', '휘발유 336경유 9'],
 ['', '14', '등급별 보기', 'GLB-Class', '337그래프로 보기', '1.8%', '64273▲', '0337▲'],
 ['', '', '', 'GLB200d', '55', '', '', ''],
 ['', '', '', 'GLB220', '93', '', '', ''],
 ['', '', '', 'GLB250 4MATIC', '189', '', '', ''],
 ['', '', '', '총합계 :', '337', '휘발유 282경유 55', '휘발유 282경유 55', '휘발유 282경유 55'],
 ['', '15', '등급별 보기', '6 Series', '303그래프로 보기', '1.6%', '36360▼', '0303▲'],
 ['', '', '', '620d Gran Turismo', '103', '', '', ''],
 ['', '', '', '620d xDrive Gran Turismo', '54', '', '', ''],
 ['', '', '', '630i xDrive Gran Turismo', '123', '', '', ''],
 ['', '', '', '630d xDrive Gran Turismo', '13', '', '', ''],
 ['', '', '', '640i xDrive Gran Turismo', '10', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '303',
  '휘발유 133경유 170',
  '휘발유 133경유 170',
  '휘발유 133경유 170'],
 ['', '16', '등급별 보기', 'X3', '301그래프로 보기', '1.6%', '421120▼', '22378▲'],
 ['', '', '', '20i', '183', '', '', ''],
 ['', '', '', '20d', '52', '', '', ''],
 ['', '', '', '30d', '3', '', '', ''],
 ['', '', '', '30e', '41', '', '', ''],
 ['', '', '', 'M40i', '22', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '301',
  '휘발유 205경유 55하이브리드 41',
  '휘발유 205경유 55하이브리드 41',
  '휘발유 205경유 55하이브리드 41'],
 ['', '17', '등급별 보기', 'XC60', '293그래프로 보기', '1.6%', '453160▼', '23756▲'],
 ['', '', '', '2.0 T8 AWD', '293', '', '', ''],
 ['', '', '', '총합계 :', '293', '하이브리드 293', '하이브리드 293', '하이브리드 293'],
 ['', '18', '등급별 보기', '7 Series', '291그래프로 보기', '1.6%', '2865▲', '103188▲'],
 ['', '', '', '730Ld xDrive', '57', '', '', ''],
 ['', '', '', '730d xDrive', '58', '', '', ''],
 ['', '', '', '740i', '44', '', '', ''],
 ['', '', '', '740Li xDrive', '88', '', '', ''],
 ['', '', '', '740d xDrive', '11', '', '', ''],
 ['', '', '', '745Le', '9', '', '', ''],
 ['', '', '', '745e', '13', '', '', ''],
 ['', '', '', 'M760Li xDrive', '11', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '291',
  '휘발유 143경유 126하이브리드 22',
  '휘발유 143경유 126하이브리드 22',
  '휘발유 143경유 126하이브리드 22'],
 ['', '19', '등급별 보기', 'Hatch', '289그래프로 보기', '1.6%', '490201▼', '25336▲'],
 ['', '', '', 'Cooper', '76', '', '', ''],
 ['', '', '', 'Cooper S', '34', '', '', ''],
 ['', '', '', 'Cooper S five-door', '21', '', '', ''],
 ['', '', '', 'Cooper five-door', '140', '', '', ''],
 ['', '', '', 'John Cooper Works', '18', '', '', ''],
 ['', '', '', '총합계 :', '289', '휘발유 289', '휘발유 289', '휘발유 289'],
 ['', '20', '등급별 보기', 'G-Class', '268그래프로 보기', '1.5%', '4264▲', '3265▲'],
 ['', '', '', 'AMG G63', '268', '', '', ''],
 ['', '', '', '총합계 :', '268', '휘발유 268', '휘발유 268', '휘발유 268'],
 ['', '21', '등급별 보기', '1 Series', '260그래프로 보기', '1.4%', '20852▲', '20240▲'],
 ['', '', '', '118d Urban', '260', '', '', ''],
 ['', '', '', '총합계 :', '260', '경유 260', '경유 260', '경유 260'],
 ['', '22', '등급별 보기', 'C-Class', '250그래프로 보기', '1.4%', '31666▼', '33585▼'],
 ['', '', '', 'C200', '50', '', '', ''],
 ['', '', '', 'C200 Cabriolet', '22', '', '', ''],
 ['', '', '', 'C200 Coupe', '20', '', '', ''],
 ['', '', '', 'C220d 4MATIC', '148', '', '', ''],
 ['', '', '', 'AMG C43 4MATIC', '6', '', '', ''],
 ['', '', '', 'AMG C43 4MATIC Coupe', '1', '', '', ''],
 ['', '', '', 'AMG C63 S Coupe', '3', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '250',
  '휘발유 102경유 148',
  '휘발유 102경유 148',
  '휘발유 102경유 148'],
 ['', '23', '등급별 보기', 'Q5', '243그래프로 보기', '1.3%', '420177▼', '0243▲'],
 ['', '', '', '40 TDI quattro', '133', '', '', ''],
 ['', '', '', '45 TFSI quattro', '3', '', '', ''],
 ['', '', '', '50 TDI quattro', '49', '', '', ''],
 ['', '', '', 'SQ5 TDI', '58', '', '', ''],
 ['', '', '', '총합계 :', '243', '휘발유 3경유 240', '휘발유 3경유 240', '휘발유 3경유 240'],
 ['',
  '24',
  '등급별 보기',
  '2 Series Active Tourer',
  '232그래프로 보기',
  '1.3%',
  '333101▼',
  '0232▲'],
 ['', '', '', 'Active Tourer', '232', '', '', ''],
 ['', '', '', '총합계 :', '232', '경유 232', '경유 232', '경유 232'],
 ['', '25', '등급별 보기', 'Countryman', '211그래프로 보기', '1.1%', '335124▼', '0211▲'],
 ['', '', '', 'Cooper', '139', '', '', ''],
 ['', '', '', 'Cooper D ALL4', '36', '', '', ''],
 ['', '', '', 'Cooper S ALL4', '21', '', '', ''],
 ['', '', '', 'Cooper SD ALL4', '1', '', '', ''],
 ['', '', '', 'John Cooper Works ALL4', '14', '', '', ''],
 ['', '', '', '총합계 :', '211', '휘발유 174경유 37', '휘발유 174경유 37', '휘발유 174경유 37'],
 ['', '26', '등급별 보기', 'X4', '208그래프로 보기', '1.1%', '346138▼', '2102▼'],
 ['', '', '', '20i', '155', '', '', ''],
 ['', '', '', '20d', '41', '', '', ''],
 ['', '', '', 'M40i', '12', '', '', ''],
 ['', '', '', '총합계 :', '208', '휘발유 167경유 41', '휘발유 167경유 41', '휘발유 167경유 41'],
 ['', '27', '등급별 보기', 'GLS-Class', '202그래프로 보기', '1.1%', '22180▲', '0202▲'],
 ['', '', '', 'GLS400d 4MATIC', '202', '', '', ''],
 ['', '', '', '총합계 :', '202', '경유 202', '경유 202', '경유 202'],
 ['', '28', '등급별 보기', 'S-Class', '200그래프로 보기', '1.1%', '316116▼', '952752▼'],
 ['', '', '', 'AMG S63 4MATIC+ Coupe', '4', '', '', ''],
 ['', '', '', 'AMG S63 4MATIC+ L', '10', '', '', ''],
 ['', '', '', 'AMG S63 4MATIC Coupe', '6', '', '', ''],
 ['', '', '', 'S350 Long', '8', '', '', ''],
 ['', '', '', 'S350d 4MATIC', '56', '', '', ''],
 ['', '', '', 'S450 4MATIC Coupe', '2', '', '', ''],
 ['', '', '', 'S450 4MATIC Long', '28', '', '', ''],
 ['', '', '', 'S560 4MATIC Long', '60', '', '', ''],
 ['', '', '', 'S560e', '26', '', '', ''],
 ['',
  '',
  '',
  '총합계 :',
  '200',
  '휘발유 118경유 56하이브리드 26',
  '휘발유 118경유 56하이브리드 26',
  '휘발유 118경유 56하이브리드 26'],
 ['', '29', '등급별 보기', 'XC40', '199그래프로 보기', '1.1%', '11089▲', '12277▲'],
 ['', '', '', 'B4 AWD', '199', '', '', ''],
 ['', '', '', '총합계 :', '199', '휘발유 199', '휘발유 199', '휘발유 199'],
 ['', '30', '등급별 보기', 'S60', '197그래프로 보기', '1.1%', '25861▼', '22629▼'],
 ['', '', '', 'B5', '197', '', '', ''],
 ['', '', '', '총합계 :', '197', '휘발유 197', '휘발유 197', '휘발유 197'],
 ['', '31', '등급별 보기', 'A4', '188그래프로 보기', '1.0%', '1968▼', '0188▲'],
 ['', '', '', '35 TDI', '78', '', '', ''],
 ['', '', '', '40 TDI quattro', '12', '', '', ''],
 ['', '', '', '40 TFSI', '98', '', '', ''],
 ['', '', '', '총합계 :', '188', '휘발유 98경유 90', '휘발유 98경유 90', '휘발유 98경유 90'],
 ['', '32', '등급별 보기', 'S90', '183그래프로 보기', '1.0%', '10677▲', '0183▲'],
 ['', '', '', 'B5', '183', '', '', ''],
 ['', '', '', '총합계 :', '183', '휘발유 183', '휘발유 183', '휘발유 183'],
 ['', '33', '등급별 보기', 'Clubman', '182그래프로 보기', '1.0%', '22846▼', '10478▲'],
 ['', '', '', 'Cooper', '136', '', '', ''],
 ['', '', '', 'Cooper D', '14', '', '', ''],
 ['', '', '', 'Cooper S', '21', '', '', ''],
 ['', '', '', 'Cooper SD', '1', '', '', ''],
 ['', '', '', 'John Cooper Works ALL4', '10', '', '', ''],
 ['', '', '', '총합계 :', '182', '휘발유 167경유 15', '휘발유 167경유 15', '휘발유 167경유 15'],
 ['', '34', '등급별 보기', 'A7', '170그래프로 보기', '0.9%', '22757▼', '0170▲'],
 ['', '', '', '45 TDI quattro', '19', '', '', ''],
 ['', '', '', '50 TDI quattro', '39', '', '', ''],
 ['', '', '', '55 TFSI quattro', '101', '', '', ''],
 ['', '', '', 'S7 TDI', '11', '', '', ''],
 ['', '', '', '총합계 :', '170', '휘발유 101경유 69', '휘발유 101경유 69', '휘발유 101경유 69'],
 ['', '35', '등급별 보기', 'X7', '165그래프로 보기', '0.9%', '23974▼', '46119▲'],
 ['', '', '', '30d', '2', '', '', ''],
 ['', '', '', '40i', '122', '', '', ''],
 ['', '', '', '40d', '21', '', '', ''],
 ['', '', '', 'M50i', '20', '', '', ''],
 ['', '', '', '총합계 :', '165', '휘발유 142경유 23', '휘발유 142경유 23', '휘발유 142경유 23'],
 ['', '36', '등급별 보기', 'A5', '163그래프로 보기', '0.9%', '1652▼', '0163▲'],
 ['', '', '', 'Coupe 45 TFSI quattro', '4', '', '', ''],
 ['', '', '', 'Sportback 40 TDI quattro', '150', '', '', ''],
 ['', '', '', 'Sportback 45 TFSI quattro', '9', '', '', ''],
 ['', '', '', '총합계 :', '163', '휘발유 13경유 150', '휘발유 13경유 150', '휘발유 13경유 150'],
 ['',
  '37',
  '등급별 보기',
  'The new Touareg',
  '150그래프로 보기',
  '0.8%',
  '20555▼',
  '0150▲'],
 ['', '', '', '3.0 TDI', '131', '', '', ''],
 ['', '', '', '4.0 TDI', '19', '', '', ''],
 ['', '', '', '총합계 :', '150', '경유 150', '경유 150', '경유 150'],
 ['', '38', '등급별 보기', '2 Series', '148그래프로 보기', '0.8%', '5395▲', '0148▲'],
 ['', '', '', '218d Gran Coupe', '128', '', '', ''],
 ['', '', '', '220d Gran Coupe', '1', '', '', ''],
 ['', '', '', 'M235i xDrive Gran Coupe', '19', '', '', ''],
 ['', '', '', '총합계 :', '148', '휘발유 19경유 129', '휘발유 19경유 129', '휘발유 19경유 129'],
 ['',
  '39',
  '등급별 보기',
  'V60 Cross Country',
  '139그래프로 보기',
  '0.8%',
  '1489▼',
  '12811▲'],
 ['', '', '', 'B5 AWD', '139', '', '', ''],
 ['', '', '', '총합계 :', '139', '휘발유 139', '휘발유 139', '휘발유 139'],
 ['', '40', '등급별 보기', 'Q7', '133그래프로 보기', '0.7%', '19663▼', '0133▲'],
 ['', '', '', '45 TDI quattro', '120', '', '', ''],
 ['', '', '', '50 TDI quattro', '12', '', '', ''],
 ['', '', '', '55 TFSI quattro', '1', '', '', ''],
 ['', '', '', '총합계 :', '133', '휘발유 1경유 132', '휘발유 1경유 132', '휘발유 1경유 132'],
 ['', '41', '등급별 보기', '911', '132그래프로 보기', '0.7%', '16331▼', '0132▲'],
 ['', '', '', '3.0 Carrera 4', '5', '', '', ''],
 ['', '', '', '3.0 Carrera 4 Cabriolet', '7', '', '', ''],
 ['', '', '', '3.0  Carrera 4S', '27', '', '', ''],
 ['', '', '', '3.0  Carrera 4S Cabriolet', '27', '', '', ''],
 ['', '', '', '3.0 Carrera Cabriolet', '10', '', '', ''],
 ['', '', '', '3.0 Carrera Coupe', '14', '', '', ''],
 ['', '', '', '3.0 Carrera S Cabriolet', '7', '', '', ''],
 ['', '', '', '3.0 Carrera S Coupe', '8', '', '', ''],
 ['', '', '', '3.0 Targa 4', '2', '', '', ''],
 ['', '', '', '3.0 Targa 4S', '1', '', '', ''],
 ['', '', '', '3.8 Turbo S', '13', '', '', ''],
 ['', '', '', '3.8 Turbo S Cabriolet', '11', '', '', ''],
 ['', '', '', '총합계 :', '132', '휘발유 132', '휘발유 132', '휘발유 132'],
 ['', '42', '등급별 보기', 'XC90', '129그래프로 보기', '0.7%', '15425▼', '15930▼'],
 ['', '', '', '2.0 T8 AWD', '129', '', '', ''],
 ['', '', '', '총합계 :', '129', '휘발유 129', '휘발유 129', '휘발유 129'],
 ['', '43', '등급별 보기', 'GLA-Class', '120그래프로 보기', '0.7%', '238118▼', '0120▲'],
 ['', '', '', 'GLA250 4MATIC', '120', '', '', ''],
 ['', '', '', '총합계 :', '120', '휘발유 120', '휘발유 120', '휘발유 120'],
 ['', '44', '등급별 보기', 'Q8', '120그래프로 보기', '0.7%', '277157▼', '0120▲'],
 ['', '', '', '45 TDI quattro', '25', '', '', ''],
 ['', '', '', '50 TDI quattro', '86', '', '', ''],
 ['', '', '', '55 TFSI quattro', '1', '', '', ''],
 ['', '', '', 'SQ8 TDI', '8', '', '', ''],
 ['', '', '', '총합계 :', '120', '휘발유 1경유 119', '휘발유 1경유 119', '휘발유 1경유 119'],
 ['',
  '45',
  '등급별 보기',
  'The new Passat GT',
  '116그래프로 보기',
  '0.6%',
  '16100▲',
  '0116▲'],
 ['', '', '', '2.0 TDI', '104', '', '', ''],
 ['', '', '', '2.0 TDI 4Motion', '12', '', '', ''],
 ['', '', '', '총합계 :', '116', '경유 116', '경유 116', '경유 116'],
 ['', '46', '등급별 보기', 'Taycan', '105그래프로 보기', '0.6%', '4263▲', '0105▲'],
 ['', '', '', 'Taycan 4S', '105', '', '', ''],
 ['', '', '', '총합계 :', '105', '전기 105', '전기 105', '전기 105'],
 ['',
  '47',
  '등급별 보기',
  'Discovery Sport',
  '103그래프로 보기',
  '0.6%',
  '14845▼',
  '4657▲'],
 ['', '', '', 'D150', '38', '', '', ''],
 ['', '', '', 'D180', '18', '', '', ''],
 ['', '', '', 'P250', '47', '', '', ''],
 ['', '', '', '총합계 :', '103', '휘발유 47경유 56', '휘발유 47경유 56', '휘발유 47경유 56'],
 ['', '48', '등급별 보기', 'Defender', '101그래프로 보기', '0.5%', '18281▼', '0101▲'],
 ['', '', '', '110 D240', '101', '', '', ''],
 ['', '', '', '총합계 :', '101', '경유 101', '경유 101', '경유 101'],
 ['', '49', '등급별 보기', 'A8', '87그래프로 보기', '0.5%', '12336▼', '1572▲'],
 ['', '', '', '50 TDI quattro', '11', '', '', ''],
 ['', '', '', 'L 50 TDI quattro', '27', '', '', ''],
 ['', '', '', 'L 55 TFSI quattro', '40', '', '', ''],
 ['', '', '', 'L 60 TFSI quattro', '8', '', '', ''],
 ['', '', '', 'S8 L TFSI', '1', '', '', ''],
 ['', '', '', '총합계 :', '87', '휘발유 49경유 38', '휘발유 49경유 38', '휘발유 49경유 38'],
 ['', '50', '등급별 보기', 'X2', '81그래프로 보기', '0.4%', '3843▲', '5625▲'],
 ['', '', '', '18d', '25', '', '', ''],
 ['', '', '', '20i', '56', '', '', ''],
 ['', '', '', '총합계 :', '81', '휘발유 56경유 25', '휘발유 56경유 25', '휘발유 56경유 25'],
 ['', '51', '등급별 보기', 'CLA-Class', '79그래프로 보기', '0.4%', '220141▼', '079▲'],
 ['', '', '', 'CLA250 4MATIC', '79', '', '', ''],
 ['', '', '', '총합계 :', '79', '휘발유 79', '휘발유 79', '휘발유 79'],
 ['', '52', '등급별 보기', 'Q3', '69그래프로 보기', '0.4%', '427358▼', '069▲'],
 ['', '', '', '35 TDI', '23', '', '', ''],
 ['', '', '', 'Sportback 35 TDI', '46', '', '', ''],
 ['', '', '', '총합계 :', '69', '경유 69', '경유 69', '경유 69'],
 ['', '53', '등급별 보기', 'Range Rover', '49그래프로 보기', '0.3%', '3910▲', '481▲'],
 ['', '', '', '4.4 SDV8', '7', '', '', ''],
 ['', '', '', '5.0 SC', '42', '', '', ''],
 ['', '', '', '총합계 :', '49', '휘발유 42경유 7', '휘발유 42경유 7', '휘발유 42경유 7'],
 ['',
  '54',
  '등급별 보기',
  'V90 Cross Country',
  '46그래프로 보기',
  '0.2%',
  '7933▼',
  '046▲'],
 ['', '', '', 'B5 AWD', '46', '', '', ''],
 ['', '', '', '총합계 :', '46', '휘발유 46', '휘발유 46', '휘발유 46'],
 ['', '55', '등급별 보기', 'T-Roc', '40그래프로 보기', '0.2%', '040▲', '040▲'],
 ['', '', '', '2.0 TDI', '40', '', '', ''],
 ['', '', '', '총합계 :', '40', '경유 40', '경유 40', '경유 40'],
 ['', '56', '등급별 보기', '3008', '37그래프로 보기', '0.2%', '10366▼', '447▼'],
 ['', '', '', '1.5 BLUe-HDi', '32', '', '', ''],
 ['', '', '', 'GT 2.0 BLUe-HDi', '5', '', '', ''],
 ['', '', '', '총합계 :', '37', '경유 37', '경유 37', '경유 37'],
 ['',
  '57',
  '등급별 보기',
  'Range Rover Evoque',
  '35그래프로 보기',
  '0.2%',
  '6732▼',
  '5419▼'],
 ['', '', '', 'D150', '25', '', '', ''],
 ['', '', '', 'D180', '8', '', '', ''],
 ['', '', '', 'P250', '2', '', '', ''],
 ['', '', '', '총합계 :', '35', '휘발유 2경유 33', '휘발유 2경유 33', '휘발유 2경유 33'],
 ['', '58', '등급별 보기', 'Q2', '33그래프로 보기', '0.2%', '11380▼', '033▲'],
 ['', '', '', '35 TDI', '33', '', '', ''],
 ['', '', '', '총합계 :', '33', '경유 33', '경유 33', '경유 33'],
 ['', '59', '등급별 보기', 'E-Pace', '32그래프로 보기', '0.2%', '266▲', '1913▲'],
 ['', '', '', 'D180', '14', '', '', ''],
 ['', '', '', 'P250', '18', '', '', ''],
 ['', '', '', '총합계 :', '32', '휘발유 18경유 14', '휘발유 18경유 14', '휘발유 18경유 14'],
 ['', '60', '등급별 보기', 'Convertible', '30그래프로 보기', '0.2%', '4010▼', '723▲'],
 ['', '', '', 'Cooper', '10', '', '', ''],
 ['', '', '', 'Cooper S', '13', '', '', ''],
 ['', '', '', 'John Cooper Works', '7', '', '', ''],
 ['', '', '', '총합계 :', '30', '휘발유 30', '휘발유 30', '휘발유 30'],
 ['', '61', '등급별 보기', 'New 4 Series', '29그래프로 보기', '0.2%', '029▲', '029▲'],
 ['', '', '', '420i Coupe', '21', '', '', ''],
 ['', '', '', 'M440i xDrive Coupe', '8', '', '', ''],
 ['', '', '', '총합계 :', '29', '휘발유 29', '휘발유 29', '휘발유 29'],
 ['', '62', '등급별 보기', '8 Series', '29그래프로 보기', '0.2%', '378▼', '1217▲'],
 ['', '', '', '840i xDrive Gran Coupe', '26', '', '', ''],
 ['', '', '', '840d xDrive Gran Coupe', '3', '', '', ''],
 ['', '', '', '총합계 :', '29', '휘발유 26경유 3', '휘발유 26경유 3', '휘발유 26경유 3'],
 ['', '63', '등급별 보기', 'Macan', '28그래프로 보기', '0.2%', '622▲', '028▲'],
 ['', '', '', 'Macan GTS', '28', '', '', ''],
 ['', '', '', '총합계 :', '28', '휘발유 28', '휘발유 28', '휘발유 28'],
 ['',
  '64',
  '등급별 보기',
  'Range Rover Velar',
  '27그래프로 보기',
  '0.1%',
  '4720▼',
  '6841▼'],

In [60]:
import pandas as pd
df = pd.DataFrame(p[2:], columns=p[0])
df

                                 모델       판매량    점유율   전월대비   전년대비
0                      E220d 4MATIC       356
1                              E250     1,205
2                      E300e 4MATIC       344
3                       E350 4MATIC       802
4                       E450 4MATIC         9
..  ..  ...     ...             ...       ...    ...    ...    ...
508                            X5 M         1
509                           총합계 :         1  휘발유 1  휘발유 1  휘발유 1
510     112  등급별 보기        Panamera  1그래프로 보기   0.0%    32▼    87▼
511                  3.0 Panamera 4         1
512                           총합계 :         1  휘발유 1  휘발유 1  휘발유 1

[513 rows x 8 columns]

In [ ]:
for tr in trs:
    date = tr.select('td')[0].text
    album = tr.select('td')[1].text
    title = tr.select('td')[2].text
    nation = tr.select('td')[3].text
 
    print('발매일: {0}, 앨범명: {1}, 타이틀곡: {2}, 발매국가: {3}'.format(date, album, title, nation))

In [44]:
# 상품 리스트 확인
print(goods_list)

[]

In [ ]:
for v in model_list:

In [ ]:
# 1월부터 12월 생성
option_value=[]
for i in range(1, 13):
    if i >=1 and i<10:
        option_value.append('0'+str(i)+'월')
    else:
        option_value.append(str(i)+'월')
print(option_value)

In [33]:
# 1월부터 12월까지 내용 저장
option_list =[]
for j in option_value:
    select = Select(driver.find_element_by_id('selDay'))#  월 선택
    select.select_by_visible_text(j)# 드롭다운 메뉴 값 선택 1월~12월까지
    option_list.append(j)

12월

In [34]:
print(option_list)

['01월', '02월', '03월', '04월', '05월', '06월', '07월', '08월', '09월', '10월', '11월', '12월']

In [14]:
# 검색 결과가 렌더링 될 때까지 잠시 대기
time.sleep(2)

In [ ]:
# 긁어오기
for v in option_list:
    if v.find('div', class_='prod_main_info'):
        # 상품 모델명, 판매량, 점유율, 전월대비, 전년대비
        name = v.select_one('p.prod_name > a').text.strip()
        sales = v.select_one('p.price_sect > a').text.strip()
        share = v.select_one('div.thumb_image > a > img').get('data-original')
        compare_to_previous_month = v.select_one('div.thumb_image > a > img').get('data-original')
        compare_to_previous_year = v.select_one('div.thumb_image > a > img').get('data-original')
        if img_link == None:
            img_link = v.select_one('div.thumb_image > a > img').get('src')
        print(name, price, img_link)
    print()

In [ ]:
# 엑셀 저장

In [ ]:
# 브라우저 종료