In [6]:
# pip install selenium
# pip install chromedriver-autoinstaller 
# pip install bs4
 
from selenium import webdriver
import chromedriver_autoinstaller
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import time
import pandas as pd

In [5]:
!pip install chromedriver_autoinstaller

Collecting chromedriver_autoinstaller
  Downloading chromedriver_autoinstaller-0.2.2-py3-none-any.whl (5.9 kB)
Installing collected packages: chromedriver-autoinstaller
Successfully installed chromedriver-autoinstaller-0.2.2

In [2]:
!pip install selenium

Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Requirement already satisfied: urllib3 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.4)
Installing collected packages: selenium
Successfully installed selenium-3.141.0

In [17]:
# 다나와 사이트 검색
options = Options()
options.add_argument('headless'); # headless는 화면이나 페이지 이동을 표시하지 않고 동작하는 모드

In [22]:
# webdirver 설정(Chrome, Firefox 등)
chromedriver_autoinstaller.install()
# driver = webdriver.Chrome(options=options) # 브라우저 창 안보이기
driver = webdriver.Chrome() # 브라우저 창 보이기

In [23]:
# 크롬 브라우저 내부 대기 (암묵적 대기)
driver.implicitly_wait(5)
 
# 브라우저 사이즈
driver.set_window_size(1920,1280)

In [24]:
# driver = Chrome()
driver.get(url)

In [25]:
# 페이지 이동(다나와 유럽 URL)
url = 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Month=2021-06-00&MonthTo=2021-07-00'

In [26]:
# # 페이지 내용
# print('Page Contents : {}'.format(driver.page_source))

In [27]:
from selenium.webdriver.support.ui import Select

## 브랜드별 자동화 ##

## 2. 반자동 ##

In [28]:
# 브랜드별 검색 
mft_xpath = '//*[@id="finder_newcar"]/div[1]/dl[2]/dd/ul/li[1]/button'
WebDriverWait(driver,3).until(EC.presence_of_element_located((By.XPATH,mft_xpath))).click()

## 연도별 데이터 크롤링 ##

## 1. 자동화 ##

In [43]:
# 기간 자동화
year = ['2017-01-00','2018-01-00','2019-01-00','2020-01-00','2021-01-00']

In [44]:
month_address = []

# 기간 설정 반복문
for i in year[0:4]:
    print(i)
    for j in year[1:5]:
        url2 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month={i}&MonthTo={j}'
        print(url2)
        month_address.append(url2)

2017-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2017-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2017-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2017-01-00&MonthTo=2021-01-00
2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2018-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2018-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2018-01-00&MonthTo=2021-01-00
2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2019-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2019-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2019-01-00&MonthTo=2021-01-00
2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2020-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2020-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2020-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=362&Month=2020-01-00&MonthTo=2021-01-00

In [139]:
korea_brand = [303,304,307,"312,316",326,"321,322",337,329,328]
europe_brand = [349,371,376,413,422,618,367,459,394,399,381,440,436,445,404,408,409,390,385,622]
japanchina_brand = [491,486,500,537,617]

In [140]:
korea_brand_list = []

for k in korea_brand:
    k1 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={k}&Month=2017-01-00&MonthTo=2018-01-00'
    k2 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={k}&Month=2018-01-00&MonthTo=2019-01-00'
    k3 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={k}&Month=2019-01-00&MonthTo=2020-01-00'
    k4 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={k}&Month=2020-01-00&MonthTo=2021-01-00'
    k5 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={k}&Month=2021-01-00&MonthTo=2021-05-00'
    korea_brand_list.append(k1)
    korea_brand_list.append(k2)
    korea_brand_list.append(k3)
    korea_brand_list.append(k4)
    korea_brand_list.append(k5)

In [141]:
korea_brand_list

['http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2021-01-00&MonthTo=2021-05-00']

In [142]:
len(korea_brand_list)

45

In [143]:
koreaname = ['hyundai17','hyundai18','hyundai19','hyundai20','hyundai21','genesis17','genesis18','genesis19','genesis20','genesis21','kia17','kia18','kia19','kia20','kia21','chebo17','chebo18','chebo19','chebo20','chebo21','ssangyong17','ssangyong18','ssangyong19','ssangyong20','ssangyong21','reno17','reno18','reno19','reno20','reno21','SMARTEV17','SMARTEV18','SMARTEV19','SMARTEV20','SMARTEV21','camsis17','camsis18','camsis19','camsis20','camsis21','daechang17','daechang18','daechang19','daechang20','daechang21']

In [144]:
len(koreaname)

45

In [167]:
# 크롬 브라우저 내부 대기 (암묵적 대기)
driver.get('http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2017-01-00&MonthTo=2018-01-00')

WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.124)

In [164]:
for x in korea_brand_list:
    print(x)
    driver.get('x')

http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=304&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=307&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=312,316&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=326&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=321,322&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=337&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=329&Month=2021-01-00&MonthTo=2021-05-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2017-01-00&MonthTo=2018-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2018-01-00&MonthTo=2019-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2019-01-00&MonthTo=2020-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2020-01-00&MonthTo=2021-01-00
http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=328&Month=2021-01-00&MonthTo=2021-05-00

In [152]:
data=[]

In [163]:
# 기간 선택 반복
for x in korea_brand_list:
    print(x)
    for k in df:
        for m in koreaname:
            driver.get(x)#주소창 차례대로 입력
            temp = soup.find_all('table')#테이블 정보 긁어오기
            p = parser.make2d(temp[0])#페이지 긁어오기
            df = pd.DataFrame(p[2:], columns=p[0])#데이터프레임화 
            df.to_csv(f'{m}_year_data.csv', encoding='utf-8-sig')#csv파일 저장

http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=303&Month=2017-01-00&MonthTo=2018-01-00

KeyboardInterrupt:

In [159]:
data

[                             모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5
 123     21           220d Coupe       1  0.0%

 [124 rows x 6 columns],
                              모델     판매량   점유율
 0                          520d  10,249
 1                   520d xDrive   5,712
 2                   530i xDrive   4,690
 3                          530i   4,560
 4                          530d     569
 ..  ..  ..     ...          ...     ...   ...
 119     20  등급별 보기           Z4       5  0.0%
 120                       3.5 S       3
 121                         2.8       2
 122                 총합계 : 가솔린 5       5

In [ ]:
for n in range(len(data)):
    for m in koreaname:
        df.to_csv(f'{m}_year_data.csv', encoding='utf-8-sig')#csv파일 저장

In [148]:
# 기간 선택 반복
for x in korea_brand_list:
    for m in koreaname:
        driver.get(x)#주소창 차례대로 입력
        temp = soup.find_all('table')#테이블 정보 긁어오기
        p = parser.make2d(temp[0])#페이지 긁어오기
        df = pd.DataFrame(p[2:], columns=p[0])#데이터프레임화 
        df.to_csv(f'{m}_year_data.csv', encoding='utf-8-sig')#csv파일 저장

PermissionError: [Errno 13] Permission denied: 'hyundai17_year_data.csv'

In [119]:
europe_brand_list = []

for i in europe_brand:
    e1 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={i}&Month=2017-01-00&MonthTo=2018-01-00'
    e2 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={i}&Month=2018-01-00&MonthTo=2019-01-00'
    e3 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={i}&Month=2019-01-00&MonthTo=2020-01-00'
    e4 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={i}&Month=2020-01-00&MonthTo=2021-01-00'
    e5 = f'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand={i}&Month=2021-01-00&MonthTo=2021-05-00'
    europe_brand_list.append(e1)
    europe_brand_list.append(e2)
    europe_brand_list.append(e3)
    europe_brand_list.append(e4)
    europe_brand_list.append(e5)

In [116]:
# europe_brand= list(set(europe_brand))

In [120]:
len(europe_brand)

20

In [121]:
europe_brand_list

['http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=349&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=349&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=349&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=349&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=349&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=371&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=371&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=371&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=371&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=371&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=376&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=376&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=376&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=376&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=376&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=413&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=413&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=413&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=413&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=413&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=422&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=422&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=422&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=422&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=422&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=618&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=618&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=618&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=618&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=618&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=367&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=367&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=367&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=367&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=367&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=459&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=459&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=459&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=459&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=459&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=394&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=394&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=394&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=394&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=394&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=399&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=399&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=399&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=399&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=399&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=381&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=381&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=381&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=381&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=381&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=440&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=440&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=440&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=440&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=440&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=436&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=436&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=436&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=436&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=436&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=445&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=445&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=445&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=445&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=445&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=404&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=404&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=404&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=404&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=404&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=408&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=408&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=408&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=408&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=408&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=409&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=409&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=409&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=409&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=409&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=390&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=390&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=390&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=390&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=390&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=385&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=385&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=385&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=385&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=385&Month=2021-01-00&MonthTo=2021-05-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=622&Month=2017-01-00&MonthTo=2018-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=622&Month=2018-01-00&MonthTo=2019-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=622&Month=2019-01-00&MonthTo=2020-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=622&Month=2020-01-00&MonthTo=2021-01-00',
 'http://auto.danawa.com/newcar/?Work=record&Tab=Top10&Brand=622&Month=2021-01-00&MonthTo=2021-05-00']

In [122]:
len(europe_brand_list)

100

In [46]:
#bs4 초기화
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [127]:
europename = ['benz17','benz18','benz19','benz20','benz21','audi17','audi18','audi19','audi20','audi21','fox17','fox18','fox19','fox20','fox21','puzzo17','puzzo18','puzzo19','puzzo20','puzzo21','citroen17','citroen18','citroen19','citroen20','citroen21','ds17','ds18','ds19','ds20','ds21','mini17','mini18','mini19','mini20','mini21','volvo17','volvo18','volvo19','volvo20','volvo21','jaguar17','jaguar18','jaguar19','jaguar20','jaguar21','land17','land18','land19','land20','land21','porche17','porche18','porche19','porche20','porche21','lambor17','lambor18','lambor19','lambor20','lambor21','perari17','perari18','perari19','perari20','perari21','maserati17','maserati18','maserati19','maserati20','maserati21','ester17','ester18','ester19','ester20','ester21','loters17','loters18','loters19','loters20','loters21','mcraren17','mcraren18','mcraren19','mcraren20','mcraren21','bentli17','bentli18','bentli19','bentli20','bentli21','roles17','roles18','roles19','roles20','roles21','eveco17','eveco18','eveco19','eveco20','eveco21']

In [123]:
# europename = list(set(europename))#중복제거

In [128]:
len(europename)

100

In [129]:
europename

['benz17',
 'benz18',
 'benz19',
 'benz20',
 'benz21',
 'audi17',
 'audi18',
 'audi19',
 'audi20',
 'audi21',
 'fox17',
 'fox18',
 'fox19',
 'fox20',
 'fox21',
 'puzzo17',
 'puzzo18',
 'puzzo19',
 'puzzo20',
 'puzzo21',
 'citroen17',
 'citroen18',
 'citroen19',
 'citroen20',
 'citroen21',
 'ds17',
 'ds18',
 'ds19',
 'ds20',
 'ds21',
 'mini17',
 'mini18',
 'mini19',
 'mini20',
 'mini21',
 'volvo17',
 'volvo18',
 'volvo19',
 'volvo20',
 'volvo21',
 'jaguar17',
 'jaguar18',
 'jaguar19',
 'jaguar20',
 'jaguar21',
 'land17',
 'land18',
 'land19',
 'land20',
 'land21',
 'porche17',
 'porche18',
 'porche19',
 'porche20',
 'porche21',
 'lambor17',
 'lambor18',
 'lambor19',
 'lambor20',
 'lambor21',
 'perari17',
 'perari18',
 'perari19',
 'perari20',
 'perari21',
 'maserati17',
 'maserati18',
 'maserati19',
 'maserati20',
 'maserati21',
 'ester17',
 'ester18',
 'ester19',
 'ester20',
 'ester21',
 'loters17',
 'loters18',
 'loters19',
 'loters20',
 'loters21',
 'mcraren17',
 'mcraren18',
 'mcraren19',
 'mcraren20',
 'mcraren21',
 'bentli17',
 'bentli18',
 'bentli19',
 'bentli20',
 'bentli21',
 'roles17',
 'roles18',
 'roles19',
 'roles20',
 'roles21',
 'eveco17',
 'eveco18',
 'eveco19',
 'eveco20',
 'eveco21']

In [130]:
# 기간 선택 반복
for x in europe_brand_list:
    for m in europename:
        driver.get(x)#주소창 차례대로 입력
        temp = soup.find_all('table')#테이블 정보 긁어오기 
        p = parser.make2d(temp[0])#페이지 긁어오기
        df = pd.DataFrame(p[2:], columns=p[0])#데이터프레임화 
        df.to_csv(f'{m}_year_data.csv', encoding='utf-8-sig')#csv파일 저장

KeyboardInterrupt:

## 시각화(plotly) ##

In [54]:
!pip install plotly==3.8.1
!pip install cufflinks

Collecting plotly==3.8.1
  Downloading plotly-3.8.1-py2.py3-none-any.whl (41.2 MB)
Requirement already satisfied: nbformat>=4.2 in c:\programdata\anaconda3\lib\site-packages (from plotly==3.8.1) (5.1.3)
Requirement already satisfied: pytz in c:\programdata\anaconda3\lib\site-packages (from plotly==3.8.1) (2021.1)
Collecting retrying>=1.3.3
  Downloading retrying-1.3.3.tar.gz (10 kB)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from plotly==3.8.1) (1.15.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from plotly==3.8.1) (2.25.1)
Requirement already satisfied: decorator>=4.0.6 in c:\programdata\anaconda3\lib\site-packages (from plotly==3.8.1) (5.0.6)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2->plotly==3.8.1) (3.2.0)
Requirement already satisfied: traitlets>=4.1 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2->plotly==3.8.1) (5.0.5)
Requirement already satisfied: jupyter-core in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2->plotly==3.8.1) (4.7.1)
Requirement already satisfied: ipython-genutils in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2->plotly==3.8.1) (0.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.8.1) (0.17.3)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.8.1) (52.0.0.post20210125)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.8.1) (20.3.0)
Requirement already satisfied: pywin32>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2->plotly==3.8.1) (227)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->plotly==3.8.1) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->plotly==3.8.1) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->plotly==3.8.1) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->plotly==3.8.1) (4.0.0)
Building wheels for collected packages: retrying
  Building wheel for retrying (setup.py): started
  Building wheel for retrying (setup.py): finished with status 'done'
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11429 sha256=c390f7b7b48663758c7a41b6656ab95b3080fd835cf80f9600df741a2ff620f9
  Stored in directory: c:\users\웍스컴바인\appdata\local\pip\cache\wheels\c4\a7\48\0a434133f6d56e878ca511c0e6c38326907c0792f67b476e56
Successfully built retrying
Installing collected packages: retrying, plotly
Successfully installed plotly-3.8.1 retrying-1.3.3
Collecting cufflinks
  Downloading cufflinks-0.17.3.tar.gz (81 kB)
Requirement already satisfied: numpy>=1.9.2 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (1.20.1)
Requirement already satisfied: pandas>=0.19.2 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (1.2.4)
Collecting plotly>=4.1.1
  Downloading plotly-5.1.0-py2.py3-none-any.whl (20.6 MB)
Requirement already satisfied: six>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (1.15.0)
Collecting colorlover>=0.2.1
  Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Requirement already satisfied: setuptools>=34.4.1 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (52.0.0.post20210125)
Requirement already satisfied: ipython>=5.3.0 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (7.22.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\programdata\anaconda3\lib\site-packages (from cufflinks) (7.6.3)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.7.5)
Requirement already satisfied: backcall in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.4)
Requirement already satisfied: pygments in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.8.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.17)
Requirement already satisfied: traitlets>=4.2 in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.0.5)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.17.2)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.0.6)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (1.0.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (5.3.4)
Requirement already satisfied: jupyter-client in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (6.1.12)
Requirement already satisfied: tornado>=4.2 in c:\programdata\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (6.1)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.7.0)
Requirement already satisfied: ipython-genutils in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (3.2.0)
Requirement already satisfied: jupyter-core in c:\programdata\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (4.7.1)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (20.3.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2021.1)
Collecting tenacity>=6.2.0
  Downloading tenacity-7.0.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->cufflinks) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\programdata\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.3.0)
Requirement already satisfied: prometheus-client in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.10.1)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.9.4)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.0.7)
Requirement already satisfied: argon2-cffi in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (20.1.0)
Requirement already satisfied: pyzmq>=17 in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (19.0.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.11.3)
Requirement already satisfied: pywin32>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (227)
Requirement already satisfied: pywinpty>=0.5 in c:\programdata\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.14.5)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.1.1)
Requirement already satisfied: testpath in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.4)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.3)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.1.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.4.3)
Requirement already satisfied: entrypoints>=0.2.2 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.3)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (3.3.0)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.5.1)
Requirement already satisfied: async-generator in c:\programdata\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.10)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (20.9)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.4.7)
Building wheels for collected packages: cufflinks
  Building wheel for cufflinks (setup.py): started
  Building wheel for cufflinks (setup.py): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68724 sha256=93a9ac75c2a7ed0d5030a9cc121ef379dd16be8c6c3f8c86729c9777673980c7
  Stored in directory: c:\users\웍스컴바인\appdata\local\pip\cache\wheels\6b\76\62\6da97734911ffcbdd559fd1a3f28526321f0ae699182a23866
Successfully built cufflinks
Installing collected packages: tenacity, plotly, colorlover, cufflinks
  Attempting uninstall: plotly
    Found existing installation: plotly 3.8.1
    Uninstalling plotly-3.8.1:
      Successfully uninstalled plotly-3.8.1
Successfully installed colorlover-0.3.0 cufflinks-0.17.3 plotly-5.1.0 tenacity-7.0.0

In [74]:
# 패키지로드
# - Standard plotly imports
import plotly.plotly as py
import cufflinks as cf
cf.go_offline(connected=True)

ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

In [ ]:
df = cf.datagen.lines()
df.head()

## 2. 반자동화 ##

In [47]:
# 상품 리스트 선택
temp = soup.find_all('table')
temp

[<table cellspacing="0" class="recordTable model">
 <caption>모델별 판매실적</caption>
 <colgroup>
 <col class="check"/>
 <col class="rank"/>
 <col class="more"/>
 <col width="*"/>
 <col class="count"/>
 <col class="rate"/>
 <col class="comp"/>
 <col class="comp"/>
 </colgroup>
 <thead>
 <tr>
 <th colspan="3"> </th>
 <th scope="col">모델</th>
 <th scope="col">판매량</th>
 <th scope="col">점유율</th>
 <th scope="col">전월대비</th>
 <th scope="col">전년대비</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td><input brand="349" name="compItemCk" title="The New E-Class" type="checkbox" value="record_3757"/></td>
 <td class="rank">1</td>
 <td><button class="viewMore" model="3757" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3757" target="_blank">
 <img alt="The New E-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3757/model_200.png"/>
                                 The New E-Class
                             </a>
 </td>
 <td class="num">2,745<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3757"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">14.9%</td>
 <td class="right">5,905<span class="down">3,160▼</span></td>
 <td class="right">0<span class="up">2,745▲</span></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E220d 4MATIC</span></td>
 <td class="num">356</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E250</span></td>
 <td class="num">1,205</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E300e 4MATIC</span></td>
 <td class="num">344</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E350 4MATIC</span></td>
 <td class="num">802</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC</span></td>
 <td class="num">9</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC Cabriolet</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>E450 4MATIC Coupe</span></td>
 <td class="num">20</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG E53 4MATIC+</span></td>
 <td class="num">3</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG E53 4MATIC+ Coupe</span></td>
 <td class="num">5</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3757" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">2,745</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>2,045</strong></span><span>경유 <strong>356</strong></span><span>하이브리드 <strong>344</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="5 Series" type="checkbox" value="record_3901"/></td>
 <td class="rank">2</td>
 <td><button class="viewMore" model="3901" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3901" target="_blank">
 <img alt="5 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3901/model_200.png"/>
                                 5 Series
                             </a>
 </td>
 <td class="num">1,730<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3901"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">9.4%</td>
 <td class="right">1,458<span class="up">272▲</span></td>
 <td class="right">0<span class="up">1,730▲</span></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>520i</span></td>
 <td class="num">622</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>523d</span></td>
 <td class="num">106</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>523d xDrive</span></td>
 <td class="num">83</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i</span></td>
 <td class="num">413</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i xDrive</span></td>
 <td class="num">258</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530e</span></td>
 <td class="num">211</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>540i xDrive</span></td>
 <td class="num">22</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M550i xDrive</span></td>
 <td class="num">15</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3901" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">1,730</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>1,330</strong></span><span>경유 <strong>189</strong></span><span>하이브리드 <strong>211</strong></span></td></tr>
 <tr>
 <td><input brand="371" name="compItemCk" title="A6" type="checkbox" value="record_3713"/></td>
 <td class="rank">3</td>
 <td><button class="viewMore" model="3713" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3713" target="_blank">
 <img alt="A6" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3713/model_200.png"/>
                                 A6
                             </a>
 </td>
 <td class="num">1,096<button brand="371" class="viewGraph" name="viewGraph" type="button" val="3713"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">6.0%</td>
 <td class="right">965<span class="up">131▲</span></td>
 <td class="right">318<span class="up">778▲</span></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40 TDI</span></td>
 <td class="num">141</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40 TDI quattro</span></td>
 <td class="num">93</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TDI quattro</span></td>
 <td class="num">55</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TFSI</span></td>
 <td class="num">425</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45 TFSI quattro</span></td>
 <td class="num">354</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>50 TDI quattro</span></td>
 <td class="num">15</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>S6 TDI</span></td>
 <td class="num">13</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3713" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">1,096</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>779</strong></span><span>경유 <strong>317</strong></span></td></tr>
 <tr>
 <td><input brand="349" name="compItemCk" title="A-Class" type="checkbox" value="record_3691"/></td>
 <td class="rank">4</td>
 <td><button class="viewMore" model="3691" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3691" target="_blank">
 <img alt="A-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3691/model_200.png"/>
                                 A-Class
                             </a>
 </td>
 <td class="num">832<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3691"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">4.5%</td>
 <td class="right">506<span class="up">326▲</span></td>
 <td class="right">20<span class="up">812▲</span></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A200d</span></td>
 <td class="num">64</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A220</span></td>
 <td class="num">229</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A220 Sedan</span></td>
 <td class="num">430</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>A250 4MATIC</span></td>
 <td class="num">30</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG A35 4MATIC</span></td>
 <td class="num">31</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG A45 4MATIC</span></td>
 <td class="num">48</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3691" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">832</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>768</strong></span><span>경유 <strong>64</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="3 Series" type="checkbox" value="record_3520"/></td>
 <td class="rank">5</td>
 <td><button class="viewMore" model="3520" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3520" target="_blank">
 <img alt="3 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3520/model_200.png"/>
                                 3 Series
                             </a>
 </td>
 <td class="num">593<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3520"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">3.2%</td>
 <td class="right">791<span class="down">198▼</span></td>
 <td class="right">265<span class="up">328▲</span></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320i</span></td>
 <td class="num">369</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320i Touring</span></td>
 <td class="num">25</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d</span></td>
 <td class="num">57</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d Touring</span></td>
 <td class="num">21</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d xDrive</span></td>
 <td class="num">18</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>330e</span></td>
 <td class="num">53</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M340i</span></td>
 <td class="num">34</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M340i xDrive Touring</span></td>
 <td class="num">16</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3520" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">593</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>444</strong></span><span>경유 <strong>96</strong></span><span>하이브리드 <strong>53</strong></span></td></tr>
 <tr>
 <td><input brand="376" name="compItemCk" title="Tiguan" type="checkbox" value="record_3368"/></td>
 <td class="rank">6</td>
 <td><button class="viewMore" model="3368" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3368" target="_blank">
 <img alt="Tiguan" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3368/model_200.png"/>
                                 Tiguan
                             </a>
 </td>
 <td class="num">565<button brand="376" class="viewGraph" name="viewGraph" type="button" val="3368"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">3.1%</td>
 <td class="right">327<span class="up">238▲</span></td>
 <td class="right">564<span class="up">1▲</span></td>
 </tr>
 <tr class="sub model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>2.0 TDI</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>Allspace 2.0 TDI</span></td>
 <td class="num">564</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3368" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">565</td>
 <td class="total_cont" colspan="3"><span>경유 <strong>565</strong></span></td></tr>
 <tr>
 <td><input brand="349" name="compItemCk" title="GLC-Class" type="checkbox" value="record_3707"/></td>
 <td class="rank">7</td>
 <td><button class="viewMore" model="3707" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3707" target="_blank">
 <img alt="GLC-Class" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3707/model_200.png"/>
                                 GLC-Class
                             </a>
 </td>
 <td class="num">467<button brand="349" class="viewGraph" name="viewGraph" type="button" val="3707"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.5%</td>
 <td class="right">1,108<span class="down">641▼</span></td>
 <td class="right">788<span class="down">321▼</span></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC220d 4MATIC</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC220d 4MATIC Coupe</span></td>
 <td class="num">1</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC300e 4MATIC</span></td>
 <td class="num">254</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GLC300e 4MATIC Coupe</span></td>
 <td class="num">204</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>AMG GLC43 4MATIC</span></td>
 <td class="num">7</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3707" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">467</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>7</strong></span><span>경유 <strong>2</strong></span><span>하이브리드 <strong>458</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="X5" type="checkbox" value="record_3577"/></td>
 <td class="rank">8</td>
 <td><button class="viewMore" model="3577" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3577" target="_blank">
 <img alt="X5" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3577/model_200.png"/>
                                 X5
                             </a>
 </td>
 <td class="num">466<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3577"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.5%</td>
 <td class="right">424<span class="up">42▲</span></td>
 <td class="right">210<span class="up">256▲</span></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>
 <td class="num">189</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40i</span></td>
 <td class="num">177</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40d</span></td>
 <td class="num">44</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>45e</span></td>
 <td class="num">35</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M50i</span></td>
 <td class="num">21</td>
 <td colspan="3"></td>
 </tr>
 <tr class="sub total model_3577" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 :</td>
 <td class="total_num">466</td>
 <td class="total_cont" colspan="3"><span>휘발유 <strong>198</strong></span><span>경유 <strong>233</strong></span><span>하이브리드 <strong>35</strong></span></td></tr>
 <tr>
 <td><input brand="362" name="compItemCk" title="X6" type="checkbox" value="record_3761"/></td>
 <td class="rank">9</td>
 <td><button class="viewMore" model="3761" name="sub_model_sel" type="button"><span class="screen_behind">등급별 보기</span></button></td>
 <td class="title">
 <a href="/auto/?Work=model&amp;Model=3761" target="_blank">
 <img alt="X6" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3761/model_200.png"/>
                                 X6
                             </a>
 </td>
 <td class="num">415<button brand="362" class="viewGraph" name="viewGraph" type="button" val="3761"><span class="screen_behind">그래프로 보기</span></button></td>
 <td class="rate right">2.3%</td>
 <td class="right">313<span class="up">102▲</span></td>
 <td class="right">70<span class="up">345▲</span></td>
 </tr>
 <tr class="sub model_3761" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>

In [30]:
!pip install html_table_parser

Collecting html_table_parser
  Downloading html_table_parser-0.1.0.tar.gz (3.4 kB)
Collecting beautifulsoup4==4.4.1
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81 kB)
Building wheels for collected packages: html-table-parser
  Building wheel for html-table-parser (setup.py): started
  Building wheel for html-table-parser (setup.py): finished with status 'done'
  Created wheel for html-table-parser: filename=html_table_parser-0.1.0-py3-none-any.whl size=4646 sha256=35fef721e9300614e3e2fa9ecce78c4268521a8622b68eba5750b5d87c8c88b8
  Stored in directory: c:\users\웍스컴바인\appdata\local\pip\cache\wheels\b8\a6\f0\e77452c538f4ab23004d6d23be1a38e39cfd45ab8a80f6709d
Successfully built html-table-parser
Installing collected packages: beautifulsoup4, html-table-parser
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.3
    Uninstalling beautifulsoup4-4.9.3:
      Successfully uninstalled beautifulsoup4-4.9.3
Successfully installed beautifulsoup4-4.4.1 html-table-parser-0.1.0

In [31]:
from html_table_parser import parser_functions as parser

In [48]:
# 2017~2018
temp = soup.find_all('table')
temp

[<table cellspacing="0" class="recordTable model">
 <caption>모델별 판매실적</caption>
 <colgroup>
 <col class="check"/>
 <col class="rank"/>
 <col class="more"/>
 <col width="*"/>
 <col class="count"/>
 <col class="rate"/>
 </colgroup>
 <thead>
 <tr>
 <th colspan="3"> </th>
 <th scope="col">모델</th>
 <th scope="col">판매량</th>
 <th scope="col">점유율</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td> </td>
 <td class="rank">1</td>
 <td>
 <button class="viewMore open" model="3422" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3422">
 <img alt="5 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3422/model_200.png"/>
                                 5 Series
                             </a>
 </td>
 <td class="num">25,968</td>
 <td>39.9%</td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>520d</span></td>
 <td class="num">10,249</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>520d xDrive</span></td>
 <td class="num">5,712</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i xDrive</span></td>
 <td class="num">4,690</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530i</span></td>
 <td class="num">4,560</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530d</span></td>
 <td class="num">569</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>530d xDrive</span></td>
 <td class="num">123</td>
 <td></td>
 </tr>
 <tr class="sub model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>540i xDrive</span></td>
 <td class="num">65</td>
 <td></td>
 </tr>
 <tr class="sub total model_3422 open" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>9,315</strong></span><span>디젤 <strong>16,653</strong></span></span></td>
 <td class="total_num">25,968</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">2</td>
 <td>
 <button class="viewMore" model="3301" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3301">
 <img alt="3 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3301/model_200.png"/>
                                 3 Series
                             </a>
 </td>
 <td class="num">12,605</td>
 <td>19.4%</td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d</span></td>
 <td class="num">6,027</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320i</span></td>
 <td class="num">2,360</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d Gran Turismo</span></td>
 <td class="num">1,877</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d xDrive Gran Turismo</span></td>
 <td class="num">946</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>330i</span></td>
 <td class="num">807</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d xDrive</span></td>
 <td class="num">343</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d ED</span></td>
 <td class="num">189</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>320d Touring</span></td>
 <td class="num">53</td>
 <td></td>
 </tr>
 <tr class="sub model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>328</span></td>
 <td class="num">3</td>
 <td></td>
 </tr>
 <tr class="sub total model_3301" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>3,170</strong></span><span>디젤 <strong>9,435</strong></span></span></td>
 <td class="total_num">12,605</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">3</td>
 <td>
 <button class="viewMore" model="3275" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3275">
 <img alt="1 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3275/model_200.png"/>
                                 1 Series
                             </a>
 </td>
 <td class="num">3,863</td>
 <td>5.9%</td>
 </tr>
 <tr class="sub model_3275" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>118d</span></td>
 <td class="num">3,863</td>
 <td></td>
 </tr>
 <tr class="sub total model_3275" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>디젤 <strong>3,863</strong></span></span></td>
 <td class="total_num">3,863</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">4</td>
 <td>
 <button class="viewMore" model="3276" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3276">
 <img alt="7 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3276/model_200.png"/>
                                 7 Series
                             </a>
 </td>
 <td class="num">3,401</td>
 <td>5.2%</td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>730Ld xDrive</span></td>
 <td class="num">1,056</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>740Li xDrive</span></td>
 <td class="num">759</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>750Li xDrive</span></td>
 <td class="num">637</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>730d xDrive</span></td>
 <td class="num">419</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>740d xDrive</span></td>
 <td class="num">298</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>740Ld xDrive</span></td>
 <td class="num">230</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>740i</span></td>
 <td class="num">1</td>
 <td></td>
 </tr>
 <tr class="sub model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>750i xDrive</span></td>
 <td class="num">1</td>
 <td></td>
 </tr>
 <tr class="sub total model_3276" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>1,398</strong></span><span>디젤 <strong>2,003</strong></span></span></td>
 <td class="total_num">3,401</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">5</td>
 <td>
 <button class="viewMore" model="3127" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3127">
 <img alt="X5" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3127/model_200.png"/>
                                 X5
                             </a>
 </td>
 <td class="num">3,310</td>
 <td>5.1%</td>
 </tr>
 <tr class="sub model_3127" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>
 <td class="num">2,747</td>
 <td></td>
 </tr>
 <tr class="sub model_3127" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40d</span></td>
 <td class="num">337</td>
 <td></td>
 </tr>
 <tr class="sub model_3127" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M50d</span></td>
 <td class="num">193</td>
 <td></td>
 </tr>
 <tr class="sub model_3127" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40e</span></td>
 <td class="num">33</td>
 <td></td>
 </tr>
 <tr class="sub total model_3127" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>디젤 <strong>3,277</strong></span><span>하이브리드 <strong>33</strong></span></span></td>
 <td class="total_num">3,310</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">6</td>
 <td>
 <button class="viewMore" model="3203" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3203">
 <img alt="X6" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3203/model_200.png"/>
                                 X6
                             </a>
 </td>
 <td class="num">2,587</td>
 <td>4.0%</td>
 </tr>
 <tr class="sub model_3203" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>30d</span></td>
 <td class="num">2,223</td>
 <td></td>
 </tr>
 <tr class="sub model_3203" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>40d</span></td>
 <td class="num">173</td>
 <td></td>
 </tr>
 <tr class="sub model_3203" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M50d</span></td>
 <td class="num">171</td>
 <td></td>
 </tr>
 <tr class="sub model_3203" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>M</span></td>
 <td class="num">20</td>
 <td></td>
 </tr>
 <tr class="sub total model_3203" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>20</strong></span><span>디젤 <strong>2,567</strong></span></span></td>
 <td class="total_num">2,587</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">7</td>
 <td>
 <button class="viewMore" model="2366" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=2366">
 <img alt="Gran Turismo" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/2366/model_200.png"/>
                                 Gran Turismo
                             </a>
 </td>
 <td class="num">2,564</td>
 <td>3.9%</td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT ED</span></td>
 <td class="num">1,561</td>
 <td></td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT 3.0d xDrive</span></td>
 <td class="num">592</td>
 <td></td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT 630d xDrive</span></td>
 <td class="num">199</td>
 <td></td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT 640i xDrive</span></td>
 <td class="num">149</td>
 <td></td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT 35i xDrive</span></td>
 <td class="num">61</td>
 <td></td>
 </tr>
 <tr class="sub model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>GT 3.0d</span></td>
 <td class="num">2</td>
 <td></td>
 </tr>
 <tr class="sub total model_2366" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>210</strong></span><span>디젤 <strong>2,354</strong></span></span></td>
 <td class="total_num">2,564</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">8</td>
 <td>
 <button class="viewMore" model="3121" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3121">
 <img alt="4 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3121/model_200.png"/>
                                 4 Series
                             </a>
 </td>
 <td class="num">1,706</td>
 <td>2.6%</td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>428i Convertible</span></td>
 <td class="num">468</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d Gran Coupe</span></td>
 <td class="num">279</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d xDrive Gran Coupe</span></td>
 <td class="num">272</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420i Gran Coupe</span></td>
 <td class="num">246</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d Coupe</span></td>
 <td class="num">168</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>428i Coupe</span></td>
 <td class="num">129</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d xDrive Coupe</span></td>
 <td class="num">115</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>435d xDrive Gran Coupe</span></td>
 <td class="num">19</td>
 <td></td>
 </tr>
 <tr class="sub model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420i Coupe</span></td>
 <td class="num">10</td>
 <td></td>
 </tr>
 <tr class="sub total model_3121" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>가솔린 <strong>853</strong></span><span>디젤 <strong>853</strong></span></span></td>
 <td class="total_num">1,706</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">9</td>
 <td>
 <button class="viewMore" model="2371" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=2371">
 <img alt="X3" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/2371/model_200.png"/>
                                 X3
                             </a>
 </td>
 <td class="num">1,483</td>
 <td>2.3%</td>
 </tr>
 <tr class="sub model_2371" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>2.0d</span></td>
 <td class="num">1,455</td>
 <td></td>
 </tr>
 <tr class="sub model_2371" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>3.0d</span></td>
 <td class="num">28</td>
 <td></td>
 </tr>
 <tr class="sub total model_2371" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>디젤 <strong>1,483</strong></span></span></td>
 <td class="total_num">1,483</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">10</td>
 <td>
 <button class="viewMore" model="3169" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3169">
 <img alt="X4" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3169/model_200.png"/>
                                 X4
                             </a>
 </td>
 <td class="num">1,427</td>
 <td>2.2%</td>
 </tr>
 <tr class="sub model_3169" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>20d</span></td>
 <td class="num">1,427</td>
 <td></td>
 </tr>
 <tr class="sub total model_3169" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>디젤 <strong>1,427</strong></span></span></td>
 <td class="total_num">1,427</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">11</td>
 <td>
 <button class="viewMore" model="3345" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3345">
 <img alt="X1" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3345/model_200.png"/>
                                 X1
                             </a>
 </td>
 <td class="num">1,282</td>
 <td>2.0%</td>
 </tr>
 <tr class="sub model_3345" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>18d</span></td>
 <td class="num">1,034</td>
 <td></td>
 </tr>
 <tr class="sub model_3345" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>20d</span></td>
 <td class="num">248</td>
 <td></td>
 </tr>
 <tr class="sub total model_3345" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="total_title">총합계 : <span class="total_cont"><span>디젤 <strong>1,282</strong></span></span></td>
 <td class="total_num">1,282</td>
 <td></td>
 </tr>
 <tr>
 <td> </td>
 <td class="rank">12</td>
 <td>
 <button class="viewMore" model="3510" name="sub_model_sel" type="button">
 <span class="screen_behind">등급별 보기</span>
 </button></td>
 <td class="title">
 <a href="/newcar/?Work=estimate&amp;Model=3510">
 <img alt="4 Series" onerror="imageError(this, 'model_200_100.png')" src="http://autoimg.danawa.com/photo/3510/model_200.png"/>
                                 4 Series
                             </a>
 </td>
 <td class="num">980</td>
 <td>1.5%</td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420i Gran Coupe</span></td>
 <td class="num">243</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>430i Convertible</span></td>
 <td class="num">185</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d Gran Coupe</span></td>
 <td class="num">176</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420i Coupe</span></td>
 <td class="num">120</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d xDrive Gran Coupe</span></td>
 <td class="num">103</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>420d Coupe</span></td>
 <td class="num">80</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>
 <td class="title"><span>430i Coupe</span></td>
 <td class="num">46</td>
 <td></td>
 </tr>
 <tr class="sub model_3510" name="sub_model">
 <td class="col" colspan="3"></td>

In [39]:
p = parser.make2d(temp[0])

In [41]:
p#ndarray

[['', '', '', '모델', '판매량', '점유율'],
 ['', '1', '등급별 보기', '5 Series', '25,968', '39.9%'],
 ['', '', '', '520d', '10,249', ''],
 ['', '', '', '520d xDrive', '5,712', ''],
 ['', '', '', '530i xDrive', '4,690', ''],
 ['', '', '', '530i', '4,560', ''],
 ['', '', '', '530d', '569', ''],
 ['', '', '', '530d xDrive', '123', ''],
 ['', '', '', '540i xDrive', '65', ''],
 ['', '', '', '총합계 : 가솔린 9,315디젤 16,653', '25,968', ''],
 ['', '2', '등급별 보기', '3 Series', '12,605', '19.4%'],
 ['', '', '', '320d', '6,027', ''],
 ['', '', '', '320i', '2,360', ''],
 ['', '', '', '320d Gran Turismo', '1,877', ''],
 ['', '', '', '320d xDrive Gran Turismo', '946', ''],
 ['', '', '', '330i', '807', ''],
 ['', '', '', '320d xDrive', '343', ''],
 ['', '', '', '320d ED', '189', ''],
 ['', '', '', '320d Touring', '53', ''],
 ['', '', '', '328', '3', ''],
 ['', '', '', '총합계 : 가솔린 3,170디젤 9,435', '12,605', ''],
 ['', '3', '등급별 보기', '1 Series', '3,863', '5.9%'],
 ['', '', '', '118d', '3,863', ''],
 ['', '', '', '총합계 : 디젤 3,863', '3,863', ''],
 ['', '4', '등급별 보기', '7 Series', '3,401', '5.2%'],
 ['', '', '', '730Ld xDrive', '1,056', ''],
 ['', '', '', '740Li xDrive', '759', ''],
 ['', '', '', '750Li xDrive', '637', ''],
 ['', '', '', '730d xDrive', '419', ''],
 ['', '', '', '740d xDrive', '298', ''],
 ['', '', '', '740Ld xDrive', '230', ''],
 ['', '', '', '740i', '1', ''],
 ['', '', '', '750i xDrive', '1', ''],
 ['', '', '', '총합계 : 가솔린 1,398디젤 2,003', '3,401', ''],
 ['', '5', '등급별 보기', 'X5', '3,310', '5.1%'],
 ['', '', '', '30d', '2,747', ''],
 ['', '', '', '40d', '337', ''],
 ['', '', '', 'M50d', '193', ''],
 ['', '', '', '40e', '33', ''],
 ['', '', '', '총합계 : 디젤 3,277하이브리드 33', '3,310', ''],
 ['', '6', '등급별 보기', 'X6', '2,587', '4.0%'],
 ['', '', '', '30d', '2,223', ''],
 ['', '', '', '40d', '173', ''],
 ['', '', '', 'M50d', '171', ''],
 ['', '', '', 'M', '20', ''],
 ['', '', '', '총합계 : 가솔린 20디젤 2,567', '2,587', ''],
 ['', '7', '등급별 보기', 'Gran Turismo', '2,564', '3.9%'],
 ['', '', '', 'GT ED', '1,561', ''],
 ['', '', '', 'GT 3.0d xDrive', '592', ''],
 ['', '', '', 'GT 630d xDrive', '199', ''],
 ['', '', '', 'GT 640i xDrive', '149', ''],
 ['', '', '', 'GT 35i xDrive', '61', ''],
 ['', '', '', 'GT 3.0d', '2', ''],
 ['', '', '', '총합계 : 가솔린 210디젤 2,354', '2,564', ''],
 ['', '8', '등급별 보기', '4 Series', '1,706', '2.6%'],
 ['', '', '', '428i Convertible', '468', ''],
 ['', '', '', '420d Gran Coupe', '279', ''],
 ['', '', '', '420d xDrive Gran Coupe', '272', ''],
 ['', '', '', '420i Gran Coupe', '246', ''],
 ['', '', '', '420d Coupe', '168', ''],
 ['', '', '', '428i Coupe', '129', ''],
 ['', '', '', '420d xDrive Coupe', '115', ''],
 ['', '', '', '435d xDrive Gran Coupe', '19', ''],
 ['', '', '', '420i Coupe', '10', ''],
 ['', '', '', '총합계 : 가솔린 853디젤 853', '1,706', ''],
 ['', '9', '등급별 보기', 'X3', '1,483', '2.3%'],
 ['', '', '', '2.0d', '1,455', ''],
 ['', '', '', '3.0d', '28', ''],
 ['', '', '', '총합계 : 디젤 1,483', '1,483', ''],
 ['', '10', '등급별 보기', 'X4', '1,427', '2.2%'],
 ['', '', '', '20d', '1,427', ''],
 ['', '', '', '총합계 : 디젤 1,427', '1,427', ''],
 ['', '11', '등급별 보기', 'X1', '1,282', '2.0%'],
 ['', '', '', '18d', '1,034', ''],
 ['', '', '', '20d', '248', ''],
 ['', '', '', '총합계 : 디젤 1,282', '1,282', ''],
 ['', '12', '등급별 보기', '4 Series', '980', '1.5%'],
 ['', '', '', '420i Gran Coupe', '243', ''],
 ['', '', '', '430i Convertible', '185', ''],
 ['', '', '', '420d Gran Coupe', '176', ''],
 ['', '', '', '420i Coupe', '120', ''],
 ['', '', '', '420d xDrive Gran Coupe', '103', ''],
 ['', '', '', '420d Coupe', '80', ''],
 ['', '', '', '430i Coupe', '46', ''],
 ['', '', '', '435d xDrive Gran Coupe', '27', ''],
 ['', '', '', '총합계 : 가솔린 594디젤 386', '980', ''],
 ['', '13', '등급별 보기', '2 Series Active Tourer', '950', '1.5%'],
 ['', '', '', 'Active Tourer', '950', ''],
 ['', '', '', '총합계 : 디젤 950', '950', ''],
 ['', '14', '등급별 보기', 'M', '924', '1.4%'],
 ['', '', '', 'M2', '254', ''],
 ['', '', '', 'M3', '162', ''],
 ['', '', '', 'M4 Coupe', '143', ''],
 ['', '', '', 'M760Li xDrive', '108', ''],
 ['', '', '', 'M4 Convertible', '103', ''],
 ['', '', '', 'M5', '101', ''],
 ['', '', '', 'M 550d xDrive', '45', ''],
 ['', '', '', 'M6 Gran Coupe', '4', ''],
 ['', '', '', 'M6 Coupe', '4', ''],
 ['', '', '', '총합계 : 가솔린 879디젤 45', '924', ''],
 ['', '15', '등급별 보기', '5 Series', '810', '1.2%'],
 ['', '', '', '520d', '289', ''],
 ['', '', '', '520d xDrive', '217', ''],
 ['', '', '', '530d xDrive', '199', ''],
 ['', '', '', '528i xDrive', '56', ''],
 ['', '', '', '528i', '49', ''],
 ['', '', '', '총합계 : 가솔린 105디젤 705', '810', ''],
 ['', '16', '등급별 보기', '6 Series', '486', '0.7%'],
 ['', '', '', '640d Gran Coupe xDrive', '478', ''],
 ['', '', '', '650i Convertible', '8', ''],
 ['', '', '', '총합계 : 가솔린 8디젤 478', '486', ''],
 ['', '17', '등급별 보기', 'X3', '363', '0.6%'],
 ['', '', '', '20d', '320', ''],
 ['', '', '', '30d', '43', ''],
 ['', '', '', '총합계 : 디젤 363', '363', ''],
 ['', '18', '등급별 보기', 'i3', '193', '0.3%'],
 ['', '', '', 'EV', '193', ''],
 ['', '', '', '총합계 : 전기 193', '193', ''],
 ['', '19', '등급별 보기', 'i8', '123', '0.2%'],
 ['', '', '', '1.5', '123', ''],
 ['', '', '', '총합계 : 하이브리드 123', '123', ''],
 ['', '20', '등급별 보기', 'Z4', '5', '0.0%'],
 ['', '', '', '3.5 S', '3', ''],
 ['', '', '', '2.8', '2', ''],
 ['', '', '', '총합계 : 가솔린 5', '5', ''],
 ['', '21', '', '220d Coupe', '1', '0.0%']]

In [42]:
import pandas as pd
df = pd.DataFrame(p[2:], columns=p[0])
df

                             모델     판매량   점유율
0                          520d  10,249
1                   520d xDrive   5,712
2                   530i xDrive   4,690
3                          530i   4,560
4                          530d     569
..  ..  ..     ...          ...     ...   ...
119     20  등급별 보기           Z4       5  0.0%
120                       3.5 S       3
121                         2.8       2
122                 총합계 : 가솔린 5       5
123     21           220d Coupe       1  0.0%

[124 rows x 6 columns]

## 연도별로 데이터 합치기 ##

## 월 별 데이터 크롤링 ##

In [ ]:
# 1월부터 12월 생성
option_value=[]
for i in range(1, 13):
    if i >=1 and i<10:
        option_value.append('0'+str(i)+'월')
    else:
        option_value.append(str(i)+'월')
print(option_value)

In [33]:
# 1월부터 12월까지 내용 저장
option_list =[]
for j in option_value:
    select = Select(driver.find_element_by_id('selDay'))#  월 선택
    select.select_by_visible_text(j)# 드롭다운 메뉴 값 선택 1월~12월까지
    option_list.append(j)

12월

In [34]:
print(option_list)

['01월', '02월', '03월', '04월', '05월', '06월', '07월', '08월', '09월', '10월', '11월', '12월']

In [14]:
# 검색 결과가 렌더링 될 때까지 잠시 대기
time.sleep(2)

In [ ]:
# 긁어오기
for v in option_list:
    if v.find('div', class_='prod_main_info'):
        # 상품 모델명, 판매량, 점유율, 전월대비, 전년대비
        name = v.select_one('p.prod_name > a').text.strip()
        sales = v.select_one('p.price_sect > a').text.strip()
        share = v.select_one('div.thumb_image > a > img').get('data-original')
        compare_to_previous_month = v.select_one('div.thumb_image > a > img').get('data-original')
        compare_to_previous_year = v.select_one('div.thumb_image > a > img').get('data-original')
        if img_link == None:
            img_link = v.select_one('div.thumb_image > a > img').get('src')
        print(name, price, img_link)
    print()

In [ ]:
# 엑셀 저장

In [ ]:
# 브라우저 종료