## 아우디 ##

In [1]:
import os
import pandas as pd

### 파일 불러오기 ###

In [2]:
df0 = pd.read_csv('C:\\Users\\웍스컴바인\\Desktop\\work\\data_analysis\\DanawaCrawler\\crawl_result\\json\\europe6\\csv파일/10.csv', encoding='utf-8')
df0
# 2017

    Unnamed: 0 car_name             sub_name  quentity
0            0       A7       50 TDI quattro       627
1            1       A7               40 TDI        36
2            2       A7       55 TDI quattro        22
3            3       A7      50 TFSI quattro         8
4            4       A7      50 TFSI quattro         8
5            5       A6       40 TDI quattro       151
6            6       A6       55 TDI quattro        68
7            7       A6      50 TFSI quattro        58
8            8       A6       50 TDI quattro        58
9            9       A6  S6 4.0 TFSI quattro         2
10          10       A6  S6 4.0 TFSI quattro         2
11          11       A4              45 TFSI        63
12          12       A4      45 TFSI quattro        11
13          13       A4       55 TDI quattro         1
14          14       A4       55 TDI quattro         1
15          15       R8   5.2 FSI Plus Coupe        43
16          16       R8   5.2 FSI Plus Coupe        43
17          17       Q5       45 TDI quattro        16
18          18       Q5  SQ5 3.0 TDI quattro         5
19          19       Q5  SQ5 3.0 TDI quattro         5
20          20       TT            TTS Coupe         5
21          21       TT            TTS Coupe         5
22          22       A8                L W12         1
23          23       A8                L W12         1
24          24       Q7       35 TDI quattro         1
25          25       Q7       35 TDI quattro         1

In [3]:
df1 = pd.read_csv('C:\\Users\\웍스컴바인\\Desktop\\work\\data_analysis\\DanawaCrawler\\crawl_result\\json\\europe6\\csv파일/11.csv', encoding='utf-8')
df1
# 2018

    Unnamed: 0 car_name            sub_name quentity
0            0       A6              35 TDI    5,194
1            1       A6      35 TDI quattro    1,551
2            2       A6             40 TFSI    1,255
3            3       A6     40 TFSI quattro      153
4            4       A6     40 TFSI quattro      153
5            5       A3             40 TFSI    3,048
6            6       A3             40 TFSI    3,048
7            7       A4              30 TDI      789
8            8       A4              35 TDI      481
9            9       A4      35 TDI quattro      409
10          10       A4      35 TDI quattro      409
11          11       A7      50 TDI quattro      214
12          12       A7      50 TDI quattro      214
13          13       R8  5.2 FSI Plus Coupe       56
14          14       R8  5.2 FSI Plus Coupe       56

In [4]:
df2 = pd.read_csv('C:\\Users\\웍스컴바인\\Desktop\\work\\data_analysis\\DanawaCrawler\\crawl_result\\json\\europe6\\csv파일/12.csv', encoding='utf-8')
df2
# 2019

    Unnamed: 0 car_name                   sub_name quentity
0            0       Q7            45 TFSI quattro    4,156
1            1       Q7            45 TFSI quattro    4,156
2            2       A6            45 TFSI quattro    2,666
3            3       A6                     40 TDI      354
4            4       A6                     40 TDI      354
5            5       A6                    40 TFSI    2,460
6            6       A6            40 TFSI quattro      100
7            7       A6            40 TFSI quattro      100
8            8       A4                    40 TFSI    1,230
9            9       A4                    40 TFSI    1,230
10          10       A5  Sportback 45 TFSI quattro    1,099
11          11       A5  Cabriolet 45 TFSI quattro       23
12          12       A5      Coupe 45 TFSI quattro       16
13          13       A5      Coupe 45 TFSI quattro       16
14          14       A3                    40 TFSI      447
15          15       A3                    40 TFSI      447
16          16       A8          L 55 TFSI quattro      142
17          17       A8          L 55 TFSI quattro      142

In [5]:
df3 = pd.read_csv('C:\\Users\\웍스컴바인\\Desktop\\work\\data_analysis\\DanawaCrawler\\crawl_result\\json\\europe6\\csv파일/13.csv', encoding='utf-8')
df3
# 2020

    Unnamed: 0 car_name                   sub_name quentity
0            0       A6                     40 TDI    4,923
1            1       A6                    45 TFSI    2,483
2            2       A6            45 TFSI quattro    2,144
3            3       A6             40 TDI quattro    1,102
4            4       A6             45 TDI quattro      840
5            5       A6             50 TDI quattro       80
6            6       A6                     S6 TDI       40
7            7       A6                     S6 TDI       40
8            8       Q3                     35 TDI    1,423
9            9       Q3           Sportback 35 TDI      736
10          10       Q3           Sportback 35 TDI      736
11          11       A7            55 TFSI quattro    1,206
12          12       A7             50 TDI quattro      700
13          13       A7             45 TDI quattro      148
14          14       A7                     S7 TDI       93
15          15       A7                     S7 TDI       93
16          16       Q5            45 TFSI quattro      987
17          17       Q5             40 TDI quattro      757
18          18       Q5             50 TDI quattro      132
19          19       Q5                    SQ5 TDI      131
20          20       Q5                    SQ5 TDI      131
21          21       A4                    40 TFSI    1,251
22          22       A4                     35 TDI       18
23          23       A4             40 TDI quattro       11
24          24       A4             40 TDI quattro       11
25          25       Q7             45 TDI quattro      900
26          26       Q7             50 TDI quattro      190
27          27       Q7             50 TDI quattro      190
28          28       Q8             50 TDI quattro      572
29          29       Q8             45 TDI quattro      285
30          30       Q8                    SQ8 TDI      139
31          31       Q8                    SQ8 TDI      139
32          32       A3                    40 TFSI      796
33          33       A3                    40 TFSI      796
34          34       A4                    40 TFSI      529
35          35       A4                     35 TDI      145
36          36       A4             40 TDI quattro       21
37          37       A4             40 TDI quattro       21
38          38       A5  Sportback 45 TFSI quattro      571
39          39       A5      Coupe 45 TFSI quattro       57
40          40       A5   Sportback 40 TDI quattro       25
41          41       A5  Cabriolet 45 TFSI quattro       16
42          42       A5  Cabriolet 45 TFSI quattro       16
43          43   e-tron                 55 quattro      601
44          44   e-tron                 55 quattro      601
45          45       A5  Sportback 45 TFSI quattro      344
46          46       A5   Sportback 40 TDI quattro      189
47          47       A5  Cabriolet 45 TFSI quattro       29
48          48       A5      Coupe 45 TFSI quattro       29
49          49       A5      Coupe 45 TFSI quattro       29
50          50       A8          L 55 TFSI quattro      265
51          51       A8           L 50 TDI quattro      171
52          52       A8             50 TDI quattro       55
53          53       A8                  S8 L TFSI       34
54          54       A8          L 60 TFSI quattro       14
55          55       A8          L 60 TFSI quattro       14
56          56       Q2                     35 TDI      329
57          57       Q2                     35 TDI      329
58          58       Q7            45 TFSI quattro        2
59          59       Q7            45 TFSI quattro        2

In [6]:
df4 = pd.read_csv('C:\\Users\\웍스컴바인\\Desktop\\work\\data_analysis\\DanawaCrawler\\crawl_result\\json\\europe6\\csv파일/14.csv', encoding='utf-8')
df4
# 2021

    Unnamed: 0         car_name                   sub_name quentity
0            0               A6                    45 TFSI    1,675
1            1               A6            45 TFSI quattro    1,553
2            2               A6                     40 TDI      762
3            3               A6             40 TDI quattro      392
4            4               A6             45 TDI quattro      315
5            5               A6             50 TDI quattro       67
6            6               A6                     S6 TDI       20
7            7               A6                     S6 TDI       20
8            8               A7            55 TFSI quattro      693
9            9               A7             50 TDI quattro      185
10          10               A7             45 TDI quattro      129
11          11               A7                     S7 TDI       44
12          12               A7                     S7 TDI       44
13          13               Q8             50 TDI quattro      338
14          14               Q8            55 TFSI quattro      236
15          15               Q8             45 TDI quattro      114
16          16               Q8                    SQ8 TDI       41
17          17               Q8                    SQ8 TDI       41
18          18               A4                    40 TFSI      410
19          19               A4                     35 TDI      102
20          20               A4            45 TFSI quattro       43
21          21               A4             40 TDI quattro       19
22          22               A4             40 TDI quattro       19
23          23               Q7             45 TDI quattro      362
24          24               Q7            55 TFSI quattro       76
25          25               Q7             50 TDI quattro       53
26          26               Q7             50 TDI quattro       53
27          27               A5   Sportback 40 TDI quattro      193
28          28               A5  Sportback 45 TFSI quattro      132
29          29               A5  Sportback 40 TFSI quattro       67
30          30               A5  Cabriolet 45 TFSI quattro       35
31          31               A5      Coupe 45 TFSI quattro       16
32          32               A5      Coupe 45 TFSI quattro       16
33          33               A8          L 55 TFSI quattro      147
34          34               A8           L 50 TDI quattro       97
35          35               A8             50 TDI quattro       54
36          36               A8          L 60 TFSI quattro       43
37          37               A8                  S8 L TFSI       11
38          38               A8                  S8 L TFSI       11
39          39               Q5             40 TDI quattro      142
40          40               Q5                    SQ5 TDI       99
41          41               Q5             50 TDI quattro       61
42          42               Q5            45 TFSI quattro        3
43          43               Q5            45 TFSI quattro        3
44          44           e-tron                 55 quattro       70
45          45           e-tron       Sportback 50 quattro        6
46          46           e-tron                 50 quattro        1
47          47           e-tron                 50 quattro        1
48          48               Q3           Sportback 35 TDI       47
49          49               Q3                     35 TDI       27
50          50               Q3                     35 TDI       27
51          51               Q2                     35 TDI       38
52          52               Q2                     35 TDI       38
53          53  The new audi R8            V10 performance       32
54          54  The new audi R8            V10 performance       32

In [7]:
# 컬럼명변경
df0 = df0.rename({'Unnamed: 0': 'year'}, axis=1)
df1 = df1.rename({'Unnamed: 0': 'year'}, axis=1)
df2 = df2.rename({'Unnamed: 0': 'year'}, axis=1)
df3 = df3.rename({'Unnamed: 0': 'year'}, axis=1)
df4 = df4.rename({'Unnamed: 0': 'year'}, axis=1)

In [8]:
df0["year"]=2017
df1["year"]=2018
df2["year"]=2019
df3["year"]=2020
df4["year"]=2021

In [9]:
df0

    year car_name             sub_name  quentity
0   2017       A7       50 TDI quattro       627
1   2017       A7               40 TDI        36
2   2017       A7       55 TDI quattro        22
3   2017       A7      50 TFSI quattro         8
4   2017       A7      50 TFSI quattro         8
5   2017       A6       40 TDI quattro       151
6   2017       A6       55 TDI quattro        68
7   2017       A6      50 TFSI quattro        58
8   2017       A6       50 TDI quattro        58
9   2017       A6  S6 4.0 TFSI quattro         2
10  2017       A6  S6 4.0 TFSI quattro         2
11  2017       A4              45 TFSI        63
12  2017       A4      45 TFSI quattro        11
13  2017       A4       55 TDI quattro         1
14  2017       A4       55 TDI quattro         1
15  2017       R8   5.2 FSI Plus Coupe        43
16  2017       R8   5.2 FSI Plus Coupe        43
17  2017       Q5       45 TDI quattro        16
18  2017       Q5  SQ5 3.0 TDI quattro         5
19  2017       Q5  SQ5 3.0 TDI quattro         5
20  2017       TT            TTS Coupe         5
21  2017       TT            TTS Coupe         5
22  2017       A8                L W12         1
23  2017       A8                L W12         1
24  2017       Q7       35 TDI quattro         1
25  2017       Q7       35 TDI quattro         1

In [10]:
df1

    year car_name            sub_name quentity
0   2018       A6              35 TDI    5,194
1   2018       A6      35 TDI quattro    1,551
2   2018       A6             40 TFSI    1,255
3   2018       A6     40 TFSI quattro      153
4   2018       A6     40 TFSI quattro      153
5   2018       A3             40 TFSI    3,048
6   2018       A3             40 TFSI    3,048
7   2018       A4              30 TDI      789
8   2018       A4              35 TDI      481
9   2018       A4      35 TDI quattro      409
10  2018       A4      35 TDI quattro      409
11  2018       A7      50 TDI quattro      214
12  2018       A7      50 TDI quattro      214
13  2018       R8  5.2 FSI Plus Coupe       56
14  2018       R8  5.2 FSI Plus Coupe       56

In [11]:
df2

    year car_name                   sub_name quentity
0   2019       Q7            45 TFSI quattro    4,156
1   2019       Q7            45 TFSI quattro    4,156
2   2019       A6            45 TFSI quattro    2,666
3   2019       A6                     40 TDI      354
4   2019       A6                     40 TDI      354
5   2019       A6                    40 TFSI    2,460
6   2019       A6            40 TFSI quattro      100
7   2019       A6            40 TFSI quattro      100
8   2019       A4                    40 TFSI    1,230
9   2019       A4                    40 TFSI    1,230
10  2019       A5  Sportback 45 TFSI quattro    1,099
11  2019       A5  Cabriolet 45 TFSI quattro       23
12  2019       A5      Coupe 45 TFSI quattro       16
13  2019       A5      Coupe 45 TFSI quattro       16
14  2019       A3                    40 TFSI      447
15  2019       A3                    40 TFSI      447
16  2019       A8          L 55 TFSI quattro      142
17  2019       A8          L 55 TFSI quattro      142

In [12]:
df3

    year car_name                   sub_name quentity
0   2020       A6                     40 TDI    4,923
1   2020       A6                    45 TFSI    2,483
2   2020       A6            45 TFSI quattro    2,144
3   2020       A6             40 TDI quattro    1,102
4   2020       A6             45 TDI quattro      840
5   2020       A6             50 TDI quattro       80
6   2020       A6                     S6 TDI       40
7   2020       A6                     S6 TDI       40
8   2020       Q3                     35 TDI    1,423
9   2020       Q3           Sportback 35 TDI      736
10  2020       Q3           Sportback 35 TDI      736
11  2020       A7            55 TFSI quattro    1,206
12  2020       A7             50 TDI quattro      700
13  2020       A7             45 TDI quattro      148
14  2020       A7                     S7 TDI       93
15  2020       A7                     S7 TDI       93
16  2020       Q5            45 TFSI quattro      987
17  2020       Q5             40 TDI quattro      757
18  2020       Q5             50 TDI quattro      132
19  2020       Q5                    SQ5 TDI      131
20  2020       Q5                    SQ5 TDI      131
21  2020       A4                    40 TFSI    1,251
22  2020       A4                     35 TDI       18
23  2020       A4             40 TDI quattro       11
24  2020       A4             40 TDI quattro       11
25  2020       Q7             45 TDI quattro      900
26  2020       Q7             50 TDI quattro      190
27  2020       Q7             50 TDI quattro      190
28  2020       Q8             50 TDI quattro      572
29  2020       Q8             45 TDI quattro      285
30  2020       Q8                    SQ8 TDI      139
31  2020       Q8                    SQ8 TDI      139
32  2020       A3                    40 TFSI      796
33  2020       A3                    40 TFSI      796
34  2020       A4                    40 TFSI      529
35  2020       A4                     35 TDI      145
36  2020       A4             40 TDI quattro       21
37  2020       A4             40 TDI quattro       21
38  2020       A5  Sportback 45 TFSI quattro      571
39  2020       A5      Coupe 45 TFSI quattro       57
40  2020       A5   Sportback 40 TDI quattro       25
41  2020       A5  Cabriolet 45 TFSI quattro       16
42  2020       A5  Cabriolet 45 TFSI quattro       16
43  2020   e-tron                 55 quattro      601
44  2020   e-tron                 55 quattro      601
45  2020       A5  Sportback 45 TFSI quattro      344
46  2020       A5   Sportback 40 TDI quattro      189
47  2020       A5  Cabriolet 45 TFSI quattro       29
48  2020       A5      Coupe 45 TFSI quattro       29
49  2020       A5      Coupe 45 TFSI quattro       29
50  2020       A8          L 55 TFSI quattro      265
51  2020       A8           L 50 TDI quattro      171
52  2020       A8             50 TDI quattro       55
53  2020       A8                  S8 L TFSI       34
54  2020       A8          L 60 TFSI quattro       14
55  2020       A8          L 60 TFSI quattro       14
56  2020       Q2                     35 TDI      329
57  2020       Q2                     35 TDI      329
58  2020       Q7            45 TFSI quattro        2
59  2020       Q7            45 TFSI quattro        2

In [13]:
df4

    year         car_name                   sub_name quentity
0   2021               A6                    45 TFSI    1,675
1   2021               A6            45 TFSI quattro    1,553
2   2021               A6                     40 TDI      762
3   2021               A6             40 TDI quattro      392
4   2021               A6             45 TDI quattro      315
5   2021               A6             50 TDI quattro       67
6   2021               A6                     S6 TDI       20
7   2021               A6                     S6 TDI       20
8   2021               A7            55 TFSI quattro      693
9   2021               A7             50 TDI quattro      185
10  2021               A7             45 TDI quattro      129
11  2021               A7                     S7 TDI       44
12  2021               A7                     S7 TDI       44
13  2021               Q8             50 TDI quattro      338
14  2021               Q8            55 TFSI quattro      236
15  2021               Q8             45 TDI quattro      114
16  2021               Q8                    SQ8 TDI       41
17  2021               Q8                    SQ8 TDI       41
18  2021               A4                    40 TFSI      410
19  2021               A4                     35 TDI      102
20  2021               A4            45 TFSI quattro       43
21  2021               A4             40 TDI quattro       19
22  2021               A4             40 TDI quattro       19
23  2021               Q7             45 TDI quattro      362
24  2021               Q7            55 TFSI quattro       76
25  2021               Q7             50 TDI quattro       53
26  2021               Q7             50 TDI quattro       53
27  2021               A5   Sportback 40 TDI quattro      193
28  2021               A5  Sportback 45 TFSI quattro      132
29  2021               A5  Sportback 40 TFSI quattro       67
30  2021               A5  Cabriolet 45 TFSI quattro       35
31  2021               A5      Coupe 45 TFSI quattro       16
32  2021               A5      Coupe 45 TFSI quattro       16
33  2021               A8          L 55 TFSI quattro      147
34  2021               A8           L 50 TDI quattro       97
35  2021               A8             50 TDI quattro       54
36  2021               A8          L 60 TFSI quattro       43
37  2021               A8                  S8 L TFSI       11
38  2021               A8                  S8 L TFSI       11
39  2021               Q5             40 TDI quattro      142
40  2021               Q5                    SQ5 TDI       99
41  2021               Q5             50 TDI quattro       61
42  2021               Q5            45 TFSI quattro        3
43  2021               Q5            45 TFSI quattro        3
44  2021           e-tron                 55 quattro       70
45  2021           e-tron       Sportback 50 quattro        6
46  2021           e-tron                 50 quattro        1
47  2021           e-tron                 50 quattro        1
48  2021               Q3           Sportback 35 TDI       47
49  2021               Q3                     35 TDI       27
50  2021               Q3                     35 TDI       27
51  2021               Q2                     35 TDI       38
52  2021               Q2                     35 TDI       38
53  2021  The new audi R8            V10 performance       32
54  2021  The new audi R8            V10 performance       32

In [14]:
# 합치기
result = pd.concat([df0, df1, df2, df3, df4])
result

    year         car_name         sub_name quentity
0   2017               A7   50 TDI quattro      627
1   2017               A7           40 TDI       36
2   2017               A7   55 TDI quattro       22
3   2017               A7  50 TFSI quattro        8
4   2017               A7  50 TFSI quattro        8
..   ...              ...              ...      ...
50  2021               Q3           35 TDI       27
51  2021               Q2           35 TDI       38
52  2021               Q2           35 TDI       38
53  2021  The new audi R8  V10 performance       32
54  2021  The new audi R8  V10 performance       32

[174 rows x 4 columns]

In [15]:
result.to_csv("Audi2017_2021.csv")